# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dw_inputs_fields.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(703, 557)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.dockWidgetContents)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.fontComboBox = QtGui.QFontComboBox(self.dockWidgetContents)
        self.fontComboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.fontComboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fontComboBox.setObjectName(_fromUtf8("fontComboBox"))
        self.gridLayout.addWidget(self.fontComboBox, 1, 1, 1, 1)
        self.fontComboBoxDis = QtGui.QFontComboBox(self.dockWidgetContents)
        self.fontComboBoxDis.setEnabled(False)
        self.fontComboBoxDis.setMinimumSize(QtCore.QSize(0, 0))
        self.fontComboBoxDis.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fontComboBoxDis.setObjectName(_fromUtf8("fontComboBoxDis"))
        self.gridLayout.addWidget(self.fontComboBoxDis, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBoxEdit = QtGui.QComboBox(self.dockWidgetContents)
        self.comboBoxEdit.setEditable(True)
        self.comboBoxEdit.setObjectName(_fromUtf8("comboBoxEdit"))
        self.comboBoxEdit.addItem(_fromUtf8(""))
        self.comboBoxEdit.addItem(_fromUtf8(""))
        self.comboBoxEdit.addItem(_fromUtf8(""))
        self.comboBoxEdit.setItemText(2, _fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxEdit, 2, 1, 1, 1)
        self.comboBoxEditDis = QtGui.QComboBox(self.dockWidgetContents)
        self.comboBoxEditDis.setEnabled(False)
        self.comboBoxEditDis.setEditable(True)
        self.comboBoxEditDis.setObjectName(_fromUtf8("comboBoxEditDis"))
        self.comboBoxEditDis.addItem(_fromUtf8(""))
        self.comboBoxEditDis.addItem(_fromUtf8(""))
        self.comboBoxEditDis.addItem(_fromUtf8(""))
        self.comboBoxEditDis.setItemText(2, _fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxEditDis, 2, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.dockWidgetContents)
        self.label_13.setMinimumSize(QtCore.QSize(0, 0))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 1)
        self.lineEditDis = QtGui.QLineEdit(self.dockWidgetContents)
        self.lineEditDis.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditDis.sizePolicy().hasHeightForWidth())
        self.lineEditDis.setSizePolicy(sizePolicy)
        self.lineEditDis.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEditDis.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEditDis.setObjectName(_fromUtf8("lineEditDis"))
        self.gridLayout.addWidget(self.lineEditDis, 3, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.dockWidgetContents)
        self.label_14.setMinimumSize(QtCore.QSize(0, 0))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 4, 0, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.dockWidgetContents)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 4, 1, 1, 1)
        self.textEditDis = QtGui.QTextEdit(self.dockWidgetContents)
        self.textEditDis.setEnabled(False)
        self.textEditDis.setMinimumSize(QtCore.QSize(0, 0))
        self.textEditDis.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEditDis.setObjectName(_fromUtf8("textEditDis"))
        self.gridLayout.addWidget(self.textEditDis, 4, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.dockWidgetContents)
        self.label_15.setMinimumSize(QtCore.QSize(0, 0))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 5, 0, 1, 1)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.dockWidgetContents)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout.addWidget(self.plainTextEdit, 5, 1, 1, 1)
        self.plainTextEditDis = QtGui.QPlainTextEdit(self.dockWidgetContents)
        self.plainTextEditDis.setEnabled(False)
        self.plainTextEditDis.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEditDis.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plainTextEditDis.setObjectName(_fromUtf8("plainTextEditDis"))
        self.gridLayout.addWidget(self.plainTextEditDis, 5, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.dockWidgetContents)
        self.label_16.setMinimumSize(QtCore.QSize(0, 0))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 6, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.dockWidgetContents)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout.addWidget(self.spinBox, 6, 1, 1, 1)
        self.spinBoxDis = QtGui.QSpinBox(self.dockWidgetContents)
        self.spinBoxDis.setEnabled(False)
        self.spinBoxDis.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBoxDis.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinBoxDis.setObjectName(_fromUtf8("spinBoxDis"))
        self.gridLayout.addWidget(self.spinBoxDis, 6, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.dockWidgetContents)
        self.label_17.setMinimumSize(QtCore.QSize(0, 0))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 7, 0, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout.addWidget(self.doubleSpinBox, 7, 1, 1, 1)
        self.doubleSpinBoxDis = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBoxDis.setEnabled(False)
        self.doubleSpinBoxDis.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBoxDis.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.doubleSpinBoxDis.setObjectName(_fromUtf8("doubleSpinBoxDis"))
        self.gridLayout.addWidget(self.doubleSpinBoxDis, 7, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.dockWidgetContents)
        self.label_18.setMinimumSize(QtCore.QSize(0, 0))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 8, 0, 1, 1)
        self.timeEdit = QtGui.QTimeEdit(self.dockWidgetContents)
        self.timeEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.timeEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.gridLayout.addWidget(self.timeEdit, 8, 1, 1, 1)
        self.timeEditDis = QtGui.QTimeEdit(self.dockWidgetContents)
        self.timeEditDis.setEnabled(False)
        self.timeEditDis.setMinimumSize(QtCore.QSize(0, 0))
        self.timeEditDis.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.timeEditDis.setObjectName(_fromUtf8("timeEditDis"))
        self.gridLayout.addWidget(self.timeEditDis, 8, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.dockWidgetContents)
        self.label_19.setMinimumSize(QtCore.QSize(0, 0))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 9, 0, 1, 1)
        self.dateEdit = QtGui.QDateEdit(self.dockWidgetContents)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.dateEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.gridLayout.addWidget(self.dateEdit, 9, 1, 1, 1)
        self.dateEditDis = QtGui.QDateEdit(self.dockWidgetContents)
        self.dateEditDis.setEnabled(False)
        self.dateEditDis.setMinimumSize(QtCore.QSize(0, 0))
        self.dateEditDis.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dateEditDis.setObjectName(_fromUtf8("dateEditDis"))
        self.gridLayout.addWidget(self.dateEditDis, 9, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.dockWidgetContents)
        self.label_20.setMinimumSize(QtCore.QSize(0, 0))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 10, 0, 1, 1)
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.dockWidgetContents)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.dateTimeEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.gridLayout.addWidget(self.dateTimeEdit, 10, 1, 1, 1)
        self.dateTimeEditDis = QtGui.QDateTimeEdit(self.dockWidgetContents)
        self.dateTimeEditDis.setEnabled(False)
        self.dateTimeEditDis.setMinimumSize(QtCore.QSize(0, 0))
        self.dateTimeEditDis.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dateTimeEditDis.setObjectName(_fromUtf8("dateTimeEditDis"))
        self.gridLayout.addWidget(self.dateTimeEditDis, 10, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 1)
        self.label_51 = QtGui.QLabel(self.dockWidgetContents)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout.addWidget(self.label_51, 12, 0, 1, 3)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QObject.connect(self.fontComboBox, QtCore.SIGNAL(_fromUtf8("editTextChanged(QString)")), self.fontComboBoxDis.setEditText)
        QtCore.QObject.connect(self.lineEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), self.lineEditDis.setText)
        QtCore.QObject.connect(self.spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBoxDis.setValue)
        QtCore.QObject.connect(self.doubleSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleSpinBoxDis.setValue)
        QtCore.QObject.connect(self.timeEdit, QtCore.SIGNAL(_fromUtf8("timeChanged(QTime)")), self.timeEditDis.setTime)
        QtCore.QObject.connect(self.dateEdit, QtCore.SIGNAL(_fromUtf8("dateTimeChanged(QDateTime)")), self.dateEditDis.setDateTime)
        QtCore.QObject.connect(self.dateTimeEdit, QtCore.SIGNAL(_fromUtf8("dateTimeChanged(QDateTime)")), self.dateTimeEditDis.setDateTime)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "Inputs - Fields", None))
        self.label.setText(_translate("DockWidget", "Enabled", None))
        self.label_2.setText(_translate("DockWidget", "Disabled", None))
        self.label_12.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.label_12.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.label_12.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_12.setText(_translate("DockWidget", "FontComboBox", None))
        self.fontComboBox.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.fontComboBox.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.fontComboBox.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.fontComboBoxDis.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.fontComboBoxDis.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.fontComboBoxDis.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_3.setText(_translate("DockWidget", "<html><head/><body><p><span style=\" font-weight:600;\">ComboBox</span></p></body></html>", None))
        self.comboBoxEdit.setItemText(0, _translate("DockWidget", "ComboBoxEditable", None))
        self.comboBoxEdit.setItemText(1, _translate("DockWidget", "Second option", None))
        self.comboBoxEditDis.setItemText(0, _translate("DockWidget", "ComboBoxEditable", None))
        self.comboBoxEditDis.setItemText(1, _translate("DockWidget", "Second option", None))
        self.label_13.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.label_13.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.label_13.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_13.setText(_translate("DockWidget", "LineEdit", None))
        self.lineEdit.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.lineEdit.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.lineEdit.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.lineEdit.setText(_translate("DockWidget", "LineEdit", None))
        self.lineEditDis.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.lineEditDis.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.lineEditDis.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.lineEditDis.setText(_translate("DockWidget", "LineEdit", None))
        self.label_14.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.label_14.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.label_14.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_14.setText(_translate("DockWidget", "TextEdit", None))
        self.textEdit.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.textEdit.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.textEdit.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.textEdit.setHtml(_translate("DockWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextEdit</p></body></html>", None))
        self.textEditDis.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.textEditDis.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.textEditDis.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.textEditDis.setHtml(_translate("DockWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TextEdit</p></body></html>", None))
        self.label_15.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.label_15.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.label_15.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_15.setText(_translate("DockWidget", "PlainTextEdit", None))
        self.plainTextEdit.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.plainTextEdit.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.plainTextEdit.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.plainTextEdit.setPlainText(_translate("DockWidget", "PlainTextEdit", None))
        self.plainTextEditDis.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.plainTextEditDis.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.plainTextEditDis.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.plainTextEditDis.setPlainText(_translate("DockWidget", "PlainTextEdit", None))
        self.label_16.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.label_16.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.label_16.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_16.setText(_translate("DockWidget", "SpinBox", None))
        self.spinBox.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.spinBox.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.spinBox.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.spinBoxDis.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.spinBoxDis.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.spinBoxDis.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_17.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.label_17.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.label_17.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_17.setText(_translate("DockWidget", "DoubleSpinBox", None))
        self.doubleSpinBox.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.doubleSpinBox.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.doubleSpinBox.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.doubleSpinBoxDis.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.doubleSpinBoxDis.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.doubleSpinBoxDis.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_18.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.label_18.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.label_18.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_18.setText(_translate("DockWidget", "TimeEdit", None))
        self.timeEdit.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.timeEdit.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.timeEdit.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.timeEditDis.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.timeEditDis.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.timeEditDis.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_19.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.label_19.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.label_19.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_19.setText(_translate("DockWidget", "DateEdit", None))
        self.dateEdit.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.dateEdit.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.dateEdit.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.dateEditDis.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.dateEditDis.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.dateEditDis.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_20.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.label_20.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.label_20.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_20.setText(_translate("DockWidget", "TimeDateEdit", None))
        self.dateTimeEdit.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.dateTimeEdit.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.dateTimeEdit.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.dateTimeEditDis.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.dateTimeEditDis.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.dateTimeEditDis.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_51.setToolTip(_translate("DockWidget", "This is a tool tip", None))
        self.label_51.setStatusTip(_translate("DockWidget", "This is a status tip", None))
        self.label_51.setWhatsThis(_translate("DockWidget", "This is \"what is this\"", None))
        self.label_51.setText(_translate("DockWidget", "Inside DockWidget", None))

