# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dw_widgets.ui'
#
# Created: Thu Dec 13 17:14:05 2018
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(269, 306)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_81 = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.gridLayout.addWidget(self.label_81, 0, 1, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.gridLayout.addWidget(self.label_82, 0, 2, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_56.setMinimumSize(QtCore.QSize(0, 0))
        self.label_56.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 1, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.dockWidgetContents)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget.setObjectName("listWidget")
        QtWidgets.QListWidgetItem(self.listWidget)
        QtWidgets.QListWidgetItem(self.listWidget)
        QtWidgets.QListWidgetItem(self.listWidget)
        QtWidgets.QListWidgetItem(self.listWidget)
        self.gridLayout.addWidget(self.listWidget, 1, 1, 1, 1)
        self.listWidgetDis = QtWidgets.QListWidget(self.dockWidgetContents)
        self.listWidgetDis.setEnabled(False)
        self.listWidgetDis.setObjectName("listWidgetDis")
        QtWidgets.QListWidgetItem(self.listWidgetDis)
        QtWidgets.QListWidgetItem(self.listWidgetDis)
        QtWidgets.QListWidgetItem(self.listWidgetDis)
        QtWidgets.QListWidgetItem(self.listWidgetDis)
        self.gridLayout.addWidget(self.listWidgetDis, 1, 2, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_57.setMinimumSize(QtCore.QSize(0, 0))
        self.label_57.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 2, 0, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.dockWidgetContents)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.treeWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout.addWidget(self.treeWidget, 2, 1, 1, 1)
        self.treeWidgetDis = QtWidgets.QTreeWidget(self.dockWidgetContents)
        self.treeWidgetDis.setEnabled(False)
        self.treeWidgetDis.setObjectName("treeWidgetDis")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetDis)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetDis)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout.addWidget(self.treeWidgetDis, 2, 2, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_58.setMinimumSize(QtCore.QSize(0, 0))
        self.label_58.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout.addWidget(self.label_58, 3, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.dockWidgetContents)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        self.gridLayout.addWidget(self.tableWidget, 3, 1, 1, 1)
        self.tableWidgetDis = QtWidgets.QTableWidget(self.dockWidgetContents)
        self.tableWidgetDis.setEnabled(False)
        self.tableWidgetDis.setObjectName("tableWidgetDis")
        self.tableWidgetDis.setColumnCount(2)
        self.tableWidgetDis.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setItem(2, 1, item)
        self.gridLayout.addWidget(self.tableWidgetDis, 3, 2, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(QtWidgets.QApplication.translate("DockWidget", "Widgets", None, -1))
        self.label_81.setText(QtWidgets.QApplication.translate("DockWidget", "Enabled", None, -1))
        self.label_82.setText(QtWidgets.QApplication.translate("DockWidget", "Disabled", None, -1))
        self.label_56.setToolTip(QtWidgets.QApplication.translate("DockWidget", "This is a tool tip", None, -1))
        self.label_56.setStatusTip(QtWidgets.QApplication.translate("DockWidget", "This is a status tip", None, -1))
        self.label_56.setWhatsThis(QtWidgets.QApplication.translate("DockWidget", "This is \"what is this\"", None, -1))
        self.label_56.setText(QtWidgets.QApplication.translate("DockWidget", "ListWidget", None, -1))
        self.listWidget.setToolTip(QtWidgets.QApplication.translate("DockWidget", "This is a tool tip", None, -1))
        self.listWidget.setStatusTip(QtWidgets.QApplication.translate("DockWidget", "This is a status tip", None, -1))
        self.listWidget.setWhatsThis(QtWidgets.QApplication.translate("DockWidget", "This is \"what is this\"", None, -1))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtWidgets.QApplication.translate("DockWidget", "New Item", None, -1))
        self.listWidget.item(1).setText(QtWidgets.QApplication.translate("DockWidget", "New Item", None, -1))
        self.listWidget.item(2).setText(QtWidgets.QApplication.translate("DockWidget", "New Item", None, -1))
        self.listWidget.item(3).setText(QtWidgets.QApplication.translate("DockWidget", "New Item", None, -1))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidgetDis.isSortingEnabled()
        self.listWidgetDis.setSortingEnabled(False)
        self.listWidgetDis.item(0).setText(QtWidgets.QApplication.translate("DockWidget", "New Item", None, -1))
        self.listWidgetDis.item(1).setText(QtWidgets.QApplication.translate("DockWidget", "New Item", None, -1))
        self.listWidgetDis.item(2).setText(QtWidgets.QApplication.translate("DockWidget", "New Item", None, -1))
        self.listWidgetDis.item(3).setText(QtWidgets.QApplication.translate("DockWidget", "New Item", None, -1))
        self.listWidgetDis.setSortingEnabled(__sortingEnabled)
        self.label_57.setToolTip(QtWidgets.QApplication.translate("DockWidget", "This is a tool tip", None, -1))
        self.label_57.setStatusTip(QtWidgets.QApplication.translate("DockWidget", "This is a status tip", None, -1))
        self.label_57.setWhatsThis(QtWidgets.QApplication.translate("DockWidget", "This is \"what is this\"", None, -1))
        self.label_57.setText(QtWidgets.QApplication.translate("DockWidget", "TreeWidget", None, -1))
        self.treeWidget.setToolTip(QtWidgets.QApplication.translate("DockWidget", "This is a tool tip", None, -1))
        self.treeWidget.setStatusTip(QtWidgets.QApplication.translate("DockWidget", "This is a status tip", None, -1))
        self.treeWidget.setWhatsThis(QtWidgets.QApplication.translate("DockWidget", "This is \"what is this\"", None, -1))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, QtWidgets.QApplication.translate("DockWidget", "New Column", None, -1))
        self.treeWidget.headerItem().setText(1, QtWidgets.QApplication.translate("DockWidget", "New Column", None, -1))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, QtWidgets.QApplication.translate("DockWidget", "New Item", None, -1))
        self.treeWidget.topLevelItem(0).child(0).setText(0, QtWidgets.QApplication.translate("DockWidget", "New Subitem", None, -1))
        self.treeWidget.topLevelItem(0).child(0).setText(1, QtWidgets.QApplication.translate("DockWidget", "Test", None, -1))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, QtWidgets.QApplication.translate("DockWidget", "New Subitem", None, -1))
        self.treeWidget.topLevelItem(1).setText(0, QtWidgets.QApplication.translate("DockWidget", "New Item", None, -1))
        self.treeWidget.topLevelItem(1).child(0).setText(0, QtWidgets.QApplication.translate("DockWidget", "New Subitem", None, -1))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.treeWidgetDis.setSortingEnabled(True)
        self.treeWidgetDis.headerItem().setText(0, QtWidgets.QApplication.translate("DockWidget", "New Column", None, -1))
        self.treeWidgetDis.headerItem().setText(1, QtWidgets.QApplication.translate("DockWidget", "New Column", None, -1))
        __sortingEnabled = self.treeWidgetDis.isSortingEnabled()
        self.treeWidgetDis.setSortingEnabled(False)
        self.treeWidgetDis.topLevelItem(0).setText(0, QtWidgets.QApplication.translate("DockWidget", "New Item", None, -1))
        self.treeWidgetDis.topLevelItem(0).child(0).setText(0, QtWidgets.QApplication.translate("DockWidget", "New Subitem", None, -1))
        self.treeWidgetDis.topLevelItem(0).child(0).setText(1, QtWidgets.QApplication.translate("DockWidget", "Test", None, -1))
        self.treeWidgetDis.topLevelItem(0).child(0).child(0).setText(0, QtWidgets.QApplication.translate("DockWidget", "New Subitem", None, -1))
        self.treeWidgetDis.topLevelItem(1).setText(0, QtWidgets.QApplication.translate("DockWidget", "New Item", None, -1))
        self.treeWidgetDis.topLevelItem(1).child(0).setText(0, QtWidgets.QApplication.translate("DockWidget", "New Subitem", None, -1))
        self.treeWidgetDis.setSortingEnabled(__sortingEnabled)
        self.label_58.setToolTip(QtWidgets.QApplication.translate("DockWidget", "This is a tool tip", None, -1))
        self.label_58.setStatusTip(QtWidgets.QApplication.translate("DockWidget", "This is a status tip", None, -1))
        self.label_58.setWhatsThis(QtWidgets.QApplication.translate("DockWidget", "This is \"what is this\"", None, -1))
        self.label_58.setText(QtWidgets.QApplication.translate("DockWidget", "TableWidget", None, -1))
        self.tableWidget.setToolTip(QtWidgets.QApplication.translate("DockWidget", "This is a tool tip", None, -1))
        self.tableWidget.setStatusTip(QtWidgets.QApplication.translate("DockWidget", "This is a status tip", None, -1))
        self.tableWidget.setWhatsThis(QtWidgets.QApplication.translate("DockWidget", "This is \"what is this\"", None, -1))
        self.tableWidget.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("DockWidget", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("DockWidget", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("DockWidget", "New Row", None, -1))
        self.tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("DockWidget", "New Column", None, -1))
        self.tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("DockWidget", "New Column", None, -1))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.item(0, 0).setText(QtWidgets.QApplication.translate("DockWidget", "1.23", None, -1))
        self.tableWidget.item(0, 1).setText(QtWidgets.QApplication.translate("DockWidget", "Hello", None, -1))
        self.tableWidget.item(1, 0).setText(QtWidgets.QApplication.translate("DockWidget", "1,45", None, -1))
        self.tableWidget.item(1, 1).setText(QtWidgets.QApplication.translate("DockWidget", "Olá", None, -1))
        self.tableWidget.item(2, 0).setText(QtWidgets.QApplication.translate("DockWidget", "12/12/2012", None, -1))
        self.tableWidget.item(2, 1).setText(QtWidgets.QApplication.translate("DockWidget", "Oui", None, -1))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tableWidgetDis.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("DockWidget", "New Row", None, -1))
        self.tableWidgetDis.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("DockWidget", "New Row", None, -1))
        self.tableWidgetDis.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("DockWidget", "New Row", None, -1))
        self.tableWidgetDis.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("DockWidget", "New Column", None, -1))
        self.tableWidgetDis.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("DockWidget", "New Column", None, -1))
        __sortingEnabled = self.tableWidgetDis.isSortingEnabled()
        self.tableWidgetDis.setSortingEnabled(False)
        self.tableWidgetDis.item(0, 0).setText(QtWidgets.QApplication.translate("DockWidget", "1.23", None, -1))
        self.tableWidgetDis.item(0, 1).setText(QtWidgets.QApplication.translate("DockWidget", "Hello", None, -1))
        self.tableWidgetDis.item(1, 0).setText(QtWidgets.QApplication.translate("DockWidget", "1,45", None, -1))
        self.tableWidgetDis.item(1, 1).setText(QtWidgets.QApplication.translate("DockWidget", "Olá", None, -1))
        self.tableWidgetDis.item(2, 0).setText(QtWidgets.QApplication.translate("DockWidget", "12/12/2012", None, -1))
        self.tableWidgetDis.item(2, 1).setText(QtWidgets.QApplication.translate("DockWidget", "Oui", None, -1))
        self.tableWidgetDis.setSortingEnabled(__sortingEnabled)

