# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw_menus.ui'
#
# Created: Tue Feb 20 10:46:24 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 231)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_71 = QtGui.QLabel(self.centralwidget)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.verticalLayout_4.addWidget(self.label_71)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 28))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuMenuSub = QtGui.QMenu(self.menuMenu)
        self.menuMenuSub.setObjectName("menuMenuSub")
        self.menuMenuDelayed = QtGui.QMenu(self.menubar)
        self.menuMenuDelayed.setObjectName("menuMenuDelayed")
        self.menuMenuSubDelayed = QtGui.QMenu(self.menuMenuDelayed)
        self.menuMenuSubDelayed.setObjectName("menuMenuSubDelayed")
        self.menuMenuCheckale = QtGui.QMenu(self.menubar)
        self.menuMenuCheckale.setObjectName("menuMenuCheckale")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBarDelayed = QtGui.QToolBar(MainWindow)
        self.toolBarDelayed.setObjectName("toolBarDelayed")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarDelayed)
        self.toolBarCheckable = QtGui.QToolBar(MainWindow)
        self.toolBarCheckable.setObjectName("toolBarCheckable")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBarCheckable)
        self.actionActionA = QtGui.QAction(MainWindow)
        self.actionActionA.setObjectName("actionActionA")
        self.actionActionSubA = QtGui.QAction(MainWindow)
        self.actionActionSubA.setObjectName("actionActionSubA")
        self.actionActionSubB = QtGui.QAction(MainWindow)
        self.actionActionSubB.setObjectName("actionActionSubB")
        self.actionActionDelayedA = QtGui.QAction(MainWindow)
        self.actionActionDelayedA.setObjectName("actionActionDelayedA")
        self.actionActionDelayedSubA = QtGui.QAction(MainWindow)
        self.actionActionDelayedSubA.setObjectName("actionActionDelayedSubA")
        self.actionActionCheckableA = QtGui.QAction(MainWindow)
        self.actionActionCheckableA.setCheckable(True)
        self.actionActionCheckableA.setObjectName("actionActionCheckableA")
        self.actionActionCheckableSubAChecked = QtGui.QAction(MainWindow)
        self.actionActionCheckableSubAChecked.setCheckable(True)
        self.actionActionCheckableSubAChecked.setChecked(True)
        self.actionActionCheckableSubAChecked.setObjectName("actionActionCheckableSubAChecked")
        self.actionActionCheckableSubAUnchecked = QtGui.QAction(MainWindow)
        self.actionActionCheckableSubAUnchecked.setCheckable(True)
        self.actionActionCheckableSubAUnchecked.setObjectName("actionActionCheckableSubAUnchecked")
        self.menuMenuSub.addAction(self.actionActionSubA)
        self.menuMenuSub.addAction(self.actionActionSubB)
        self.menuMenu.addAction(self.actionActionA)
        self.menuMenu.addAction(self.menuMenuSub.menuAction())
        self.menuMenuSubDelayed.addAction(self.actionActionDelayedSubA)
        self.menuMenuDelayed.addAction(self.actionActionDelayedA)
        self.menuMenuDelayed.addAction(self.menuMenuSubDelayed.menuAction())
        self.menuMenuCheckale.addAction(self.actionActionCheckableA)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuMenuDelayed.menuAction())
        self.menubar.addAction(self.menuMenuCheckale.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionActionA)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionActionSubA)
        self.toolBar.addAction(self.actionActionSubB)
        self.toolBarDelayed.addAction(self.actionActionDelayedA)
        self.toolBarDelayed.addSeparator()
        self.toolBarDelayed.addAction(self.actionActionDelayedSubA)
        self.toolBarCheckable.addAction(self.actionActionCheckableA)
        self.toolBarCheckable.addSeparator()
        self.toolBarCheckable.addAction(self.actionActionCheckableSubAChecked)
        self.toolBarCheckable.addAction(self.actionActionCheckableSubAUnchecked)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("MainWindow", "Inside CentralWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenuSub.setTitle(QtGui.QApplication.translate("MainWindow", "Menu Sub", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenuDelayed.setTitle(QtGui.QApplication.translate("MainWindow", "Menu Delayed", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenuSubDelayed.setTitle(QtGui.QApplication.translate("MainWindow", "Menu Sub Delayed", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenuCheckale.setTitle(QtGui.QApplication.translate("MainWindow", "Menu Checkable", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About QDarkStyle", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tool bar actions", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarDelayed.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tool bar actions delayed", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarCheckable.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tool bar action checkable", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionA.setText(QtGui.QApplication.translate("MainWindow", "Action A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionSubA.setText(QtGui.QApplication.translate("MainWindow", "Action A Sub", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionSubA.setToolTip(QtGui.QApplication.translate("MainWindow", "Action A Sub", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionSubB.setText(QtGui.QApplication.translate("MainWindow", "Action B Sub", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionDelayedA.setText(QtGui.QApplication.translate("MainWindow", "Action Delayed A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionDelayedA.setToolTip(QtGui.QApplication.translate("MainWindow", "Action Delayed A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionDelayedSubA.setText(QtGui.QApplication.translate("MainWindow", "Action Delayed Sub A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionDelayedSubA.setToolTip(QtGui.QApplication.translate("MainWindow", "Action Delayed Sub A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionCheckableA.setText(QtGui.QApplication.translate("MainWindow", "Action Checkable A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionCheckableA.setToolTip(QtGui.QApplication.translate("MainWindow", "Action Checkable A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionCheckableSubAChecked.setText(QtGui.QApplication.translate("MainWindow", "Action Checkable Sub A Checked", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionCheckableSubAChecked.setToolTip(QtGui.QApplication.translate("MainWindow", "Action Checkable Sub A Checked", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionCheckableSubAUnchecked.setText(QtGui.QApplication.translate("MainWindow", "Action Checkable Sub A Unchecked", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionCheckableSubAUnchecked.setToolTip(QtGui.QApplication.translate("MainWindow", "Action Checkable Sub A Unchecked", None, QtGui.QApplication.UnicodeUTF8))

