# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw_views_widgets_containers.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(762, 705)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.ContainerContainers = QtGui.QWidget()
        self.ContainerContainers.setObjectName(_fromUtf8("ContainerContainers"))
        self.gridLayout_29 = QtGui.QGridLayout(self.ContainerContainers)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.groupBoxDis = QtGui.QGroupBox(self.ContainerContainers)
        self.groupBoxDis.setEnabled(False)
        self.groupBoxDis.setObjectName(_fromUtf8("groupBoxDis"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBoxDis)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_4 = QtGui.QLabel(self.groupBoxDis)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout_29.addWidget(self.groupBoxDis, 1, 2, 1, 1)
        self.toolBoxDis = QtGui.QToolBox(self.ContainerContainers)
        self.toolBoxDis.setEnabled(False)
        self.toolBoxDis.setObjectName(_fromUtf8("toolBoxDis"))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 196, 73))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.gridLayout_23 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.label_93 = QtGui.QLabel(self.page_4)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.gridLayout_23.addWidget(self.label_93, 2, 0, 1, 1)
        self.toolBoxDis.addItem(self.page_4, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 163, 38))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_24 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.label_94 = QtGui.QLabel(self.page_5)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.gridLayout_24.addWidget(self.label_94, 0, 0, 1, 1)
        self.toolBoxDis.addItem(self.page_5, _fromUtf8(""))
        self.gridLayout_29.addWidget(self.toolBoxDis, 3, 2, 1, 1)
        self.mdiAreaDis = QtGui.QMdiArea(self.ContainerContainers)
        self.mdiAreaDis.setEnabled(False)
        self.mdiAreaDis.setObjectName(_fromUtf8("mdiAreaDis"))
        self.subwindow1Dis = QtGui.QWidget()
        self.subwindow1Dis.setObjectName(_fromUtf8("subwindow1Dis"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.subwindow1Dis)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_98 = QtGui.QLabel(self.subwindow1Dis)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.verticalLayout_7.addWidget(self.label_98)
        self.subwindow2Dis = QtGui.QWidget()
        self.subwindow2Dis.setObjectName(_fromUtf8("subwindow2Dis"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.subwindow2Dis)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_99 = QtGui.QLabel(self.subwindow2Dis)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.verticalLayout_8.addWidget(self.label_99)
        self.gridLayout_29.addWidget(self.mdiAreaDis, 7, 2, 1, 1)
        self.mdiArea = QtGui.QMdiArea(self.ContainerContainers)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.subwindow1 = QtGui.QWidget()
        self.subwindow1.setObjectName(_fromUtf8("subwindow1"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.subwindow1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_28 = QtGui.QLabel(self.subwindow1)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_5.addWidget(self.label_28)
        self.subwindow2 = QtGui.QWidget()
        self.subwindow2.setObjectName(_fromUtf8("subwindow2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.subwindow2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_40 = QtGui.QLabel(self.subwindow2)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.verticalLayout_6.addWidget(self.label_40)
        self.gridLayout_29.addWidget(self.mdiArea, 7, 1, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.ContainerContainers)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page1 = QtGui.QWidget()
        self.page1.setObjectName(_fromUtf8("page1"))
        self.gridLayout_12 = QtGui.QGridLayout(self.page1)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_44 = QtGui.QLabel(self.page1)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_12.addWidget(self.label_44, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtGui.QWidget()
        self.page2.setObjectName(_fromUtf8("page2"))
        self.gridLayout_13 = QtGui.QGridLayout(self.page2)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_45 = QtGui.QLabel(self.page2)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_13.addWidget(self.label_45, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page2)
        self.gridLayout_29.addWidget(self.stackedWidget, 4, 1, 1, 1)
        self.stackedWidgetDis = QtGui.QStackedWidget(self.ContainerContainers)
        self.stackedWidgetDis.setEnabled(False)
        self.stackedWidgetDis.setObjectName(_fromUtf8("stackedWidgetDis"))
        self.page1Dis = QtGui.QWidget()
        self.page1Dis.setObjectName(_fromUtf8("page1Dis"))
        self.gridLayout_26 = QtGui.QGridLayout(self.page1Dis)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.label_95 = QtGui.QLabel(self.page1Dis)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.gridLayout_26.addWidget(self.label_95, 0, 0, 1, 1)
        self.stackedWidgetDis.addWidget(self.page1Dis)
        self.page2Dis = QtGui.QWidget()
        self.page2Dis.setObjectName(_fromUtf8("page2Dis"))
        self.gridLayout_27 = QtGui.QGridLayout(self.page2Dis)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.label_96 = QtGui.QLabel(self.page2Dis)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.gridLayout_27.addWidget(self.label_96, 0, 0, 1, 1)
        self.stackedWidgetDis.addWidget(self.page2Dis)
        self.gridLayout_29.addWidget(self.stackedWidgetDis, 4, 2, 1, 1)
        self.scrollAreaDis = QtGui.QScrollArea(self.ContainerContainers)
        self.scrollAreaDis.setEnabled(False)
        self.scrollAreaDis.setWidgetResizable(True)
        self.scrollAreaDis.setObjectName(_fromUtf8("scrollAreaDis"))
        self.scrollAreaWidgetContentsDis = QtGui.QWidget()
        self.scrollAreaWidgetContentsDis.setGeometry(QtCore.QRect(0, 0, 181, 246))
        self.scrollAreaWidgetContentsDis.setObjectName(_fromUtf8("scrollAreaWidgetContentsDis"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContentsDis)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_84 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.verticalLayout_3.addWidget(self.label_84)
        self.label_85 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.verticalLayout_3.addWidget(self.label_85)
        self.label_86 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.verticalLayout_3.addWidget(self.label_86)
        self.label_87 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.verticalLayout_3.addWidget(self.label_87)
        self.label_88 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.verticalLayout_3.addWidget(self.label_88)
        self.label_89 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.verticalLayout_3.addWidget(self.label_89)
        self.label_90 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.verticalLayout_3.addWidget(self.label_90)
        self.label_91 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.verticalLayout_3.addWidget(self.label_91)
        self.label_92 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.verticalLayout_3.addWidget(self.label_92)
        self.scrollAreaDis.setWidget(self.scrollAreaWidgetContentsDis)
        self.gridLayout_29.addWidget(self.scrollAreaDis, 2, 2, 1, 1)
        self.widget = QtGui.QWidget(self.ContainerContainers)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_17 = QtGui.QGridLayout(self.widget)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_47 = QtGui.QLabel(self.widget)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_17.addWidget(self.label_47, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.widget, 6, 1, 1, 1)
        self.label_100 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_100.setFont(font)
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.gridLayout_29.addWidget(self.label_100, 0, 1, 1, 1)
        self.frameDis = QtGui.QFrame(self.ContainerContainers)
        self.frameDis.setEnabled(False)
        self.frameDis.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameDis.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDis.setObjectName(_fromUtf8("frameDis"))
        self.gridLayout_25 = QtGui.QGridLayout(self.frameDis)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.label_3 = QtGui.QLabel(self.frameDis)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_25.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.frameDis, 5, 2, 1, 1)
        self.toolBox = QtGui.QToolBox(self.ContainerContainers)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_1 = QtGui.QWidget()
        self.page_1.setGeometry(QtCore.QRect(0, 0, 196, 73))
        self.page_1.setObjectName(_fromUtf8("page_1"))
        self.gridLayout_14 = QtGui.QGridLayout(self.page_1)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_41 = QtGui.QLabel(self.page_1)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_14.addWidget(self.label_41, 2, 0, 1, 1)
        self.toolBox.addItem(self.page_1, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 163, 38))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_15 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_42 = QtGui.QLabel(self.page_2)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_15.addWidget(self.label_42, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.gridLayout_29.addWidget(self.toolBox, 3, 1, 1, 1)
        self.frame = QtGui.QFrame(self.ContainerContainers)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_16 = QtGui.QGridLayout(self.frame)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_16.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.frame, 5, 1, 1, 1)
        self.widgetDis = QtGui.QWidget(self.ContainerContainers)
        self.widgetDis.setEnabled(False)
        self.widgetDis.setObjectName(_fromUtf8("widgetDis"))
        self.gridLayout_28 = QtGui.QGridLayout(self.widgetDis)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.label_97 = QtGui.QLabel(self.widgetDis)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.gridLayout_28.addWidget(self.label_97, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.widgetDis, 6, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.ContainerContainers)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.groupBox, 1, 1, 1, 1)
        self.label_101 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_101.setFont(font)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.gridLayout_29.addWidget(self.label_101, 0, 2, 1, 1)
        self.label_102 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_102.setFont(font)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.gridLayout_29.addWidget(self.label_102, 1, 0, 1, 1)
        self.label_103 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_103.setFont(font)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.gridLayout_29.addWidget(self.label_103, 2, 0, 1, 1)
        self.label_104 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_104.setFont(font)
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.gridLayout_29.addWidget(self.label_104, 3, 0, 1, 1)
        self.label_105 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_105.setFont(font)
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.gridLayout_29.addWidget(self.label_105, 4, 0, 1, 1)
        self.label_106 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_106.setFont(font)
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.gridLayout_29.addWidget(self.label_106, 5, 0, 1, 1)
        self.label_107 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_107.setFont(font)
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.gridLayout_29.addWidget(self.label_107, 6, 0, 1, 1)
        self.label_108 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_108.setFont(font)
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.gridLayout_29.addWidget(self.label_108, 7, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.ContainerContainers)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 181, 246))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_43 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.verticalLayout_2.addWidget(self.label_43)
        self.label_63 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.verticalLayout_2.addWidget(self.label_63)
        self.label_66 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.verticalLayout_2.addWidget(self.label_66)
        self.label_67 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.verticalLayout_2.addWidget(self.label_67)
        self.label_68 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.verticalLayout_2.addWidget(self.label_68)
        self.label_46 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.verticalLayout_2.addWidget(self.label_46)
        self.label_69 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.verticalLayout_2.addWidget(self.label_69)
        self.label_64 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.verticalLayout_2.addWidget(self.label_64)
        self.label_65 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.verticalLayout_2.addWidget(self.label_65)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_29.addWidget(self.scrollArea, 2, 1, 1, 1)
        self.tabWidget.addTab(self.ContainerContainers, _fromUtf8(""))
        self.ContainerContainersTab = QtGui.QWidget()
        self.ContainerContainersTab.setObjectName(_fromUtf8("ContainerContainersTab"))
        self.gridLayout_22 = QtGui.QGridLayout(self.ContainerContainersTab)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.tabWidgetNorth = QtGui.QTabWidget(self.ContainerContainersTab)
        self.tabWidgetNorth.setDocumentMode(False)
        self.tabWidgetNorth.setTabsClosable(True)
        self.tabWidgetNorth.setObjectName(_fromUtf8("tabWidgetNorth"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_52 = QtGui.QLabel(self.tab_7)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_8.addWidget(self.label_52, 0, 0, 1, 1)
        self.tabWidgetNorth.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_48 = QtGui.QLabel(self.tab_8)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_4.addWidget(self.label_48, 0, 0, 1, 1)
        self.tabWidgetNorth.addTab(self.tab_8, _fromUtf8(""))
        self.gridLayout_22.addWidget(self.tabWidgetNorth, 0, 0, 1, 1)
        self.tabWidgetWest = QtGui.QTabWidget(self.ContainerContainersTab)
        self.tabWidgetWest.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidgetWest.setObjectName(_fromUtf8("tabWidgetWest"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_39 = QtGui.QLabel(self.tab_5)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_3.addWidget(self.label_39, 0, 0, 1, 1)
        self.tabWidgetWest.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_54 = QtGui.QLabel(self.tab_6)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_9.addWidget(self.label_54, 0, 0, 1, 1)
        self.tabWidgetWest.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout_22.addWidget(self.tabWidgetWest, 1, 0, 1, 1)
        self.tabWidgetEast = QtGui.QTabWidget(self.ContainerContainersTab)
        self.tabWidgetEast.setTabPosition(QtGui.QTabWidget.East)
        self.tabWidgetEast.setObjectName(_fromUtf8("tabWidgetEast"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_38 = QtGui.QLabel(self.tab_3)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_2.addWidget(self.label_38, 0, 0, 1, 1)
        self.tabWidgetEast.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_55 = QtGui.QLabel(self.tab_4)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_11.addWidget(self.label_55, 0, 0, 1, 1)
        self.tabWidgetEast.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_22.addWidget(self.tabWidgetEast, 2, 0, 1, 1)
        self.tabWidgetSouth = QtGui.QTabWidget(self.ContainerContainersTab)
        self.tabWidgetSouth.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidgetSouth.setTabsClosable(True)
        self.tabWidgetSouth.setObjectName(_fromUtf8("tabWidgetSouth"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_34 = QtGui.QLabel(self.tab)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout.addWidget(self.label_34, 0, 0, 1, 1)
        self.tabWidgetSouth.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_18 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_62 = QtGui.QLabel(self.tab_2)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_18.addWidget(self.label_62, 0, 0, 1, 1)
        self.tabWidgetSouth.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_22.addWidget(self.tabWidgetSouth, 3, 0, 1, 1)
        self.tabWidget.addTab(self.ContainerContainersTab, _fromUtf8(""))
        self.ContainerWidgets = QtGui.QWidget()
        self.ContainerWidgets.setObjectName(_fromUtf8("ContainerWidgets"))
        self.gridLayout_7 = QtGui.QGridLayout(self.ContainerWidgets)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.listWidget = QtGui.QListWidget(self.ContainerWidgets)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout_7.addWidget(self.listWidget, 1, 2, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.ContainerWidgets)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        self.gridLayout_7.addWidget(self.tableWidget, 3, 2, 1, 1)
        self.treeWidget = QtGui.QTreeWidget(self.ContainerWidgets)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.treeWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.gridLayout_7.addWidget(self.treeWidget, 2, 2, 1, 1)
        self.label_58 = QtGui.QLabel(self.ContainerWidgets)
        self.label_58.setMinimumSize(QtCore.QSize(0, 0))
        self.label_58.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_7.addWidget(self.label_58, 3, 1, 1, 1)
        self.tableWidgetDis = QtGui.QTableWidget(self.ContainerWidgets)
        self.tableWidgetDis.setEnabled(False)
        self.tableWidgetDis.setObjectName(_fromUtf8("tableWidgetDis"))
        self.tableWidgetDis.setColumnCount(2)
        self.tableWidgetDis.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setItem(2, 1, item)
        self.gridLayout_7.addWidget(self.tableWidgetDis, 3, 3, 1, 1)
        self.listWidgetDis = QtGui.QListWidget(self.ContainerWidgets)
        self.listWidgetDis.setEnabled(False)
        self.listWidgetDis.setObjectName(_fromUtf8("listWidgetDis"))
        item = QtGui.QListWidgetItem()
        self.listWidgetDis.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidgetDis.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidgetDis.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidgetDis.addItem(item)
        self.gridLayout_7.addWidget(self.listWidgetDis, 1, 3, 1, 1)
        self.label_57 = QtGui.QLabel(self.ContainerWidgets)
        self.label_57.setMinimumSize(QtCore.QSize(0, 0))
        self.label_57.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_7.addWidget(self.label_57, 2, 1, 1, 1)
        self.label_56 = QtGui.QLabel(self.ContainerWidgets)
        self.label_56.setMinimumSize(QtCore.QSize(0, 0))
        self.label_56.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_7.addWidget(self.label_56, 1, 1, 1, 1)
        self.treeWidgetDis = QtGui.QTreeWidget(self.ContainerWidgets)
        self.treeWidgetDis.setEnabled(False)
        self.treeWidgetDis.setObjectName(_fromUtf8("treeWidgetDis"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidgetDis)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidgetDis)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.gridLayout_7.addWidget(self.treeWidgetDis, 2, 3, 1, 1)
        self.label_81 = QtGui.QLabel(self.ContainerWidgets)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_81.setFont(font)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.gridLayout_7.addWidget(self.label_81, 0, 2, 1, 1)
        self.label_82 = QtGui.QLabel(self.ContainerWidgets)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.gridLayout_7.addWidget(self.label_82, 0, 3, 1, 1)
        self.tabWidget.addTab(self.ContainerWidgets, _fromUtf8(""))
        self.ContainerViews = QtGui.QWidget()
        self.ContainerViews.setObjectName(_fromUtf8("ContainerViews"))
        self.gridLayout_5 = QtGui.QGridLayout(self.ContainerViews)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.treeView = QtGui.QTreeView(self.ContainerViews)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.gridLayout_5.addWidget(self.treeView, 2, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_5.addWidget(self.label_27, 1, 0, 1, 1)
        self.listView = QtGui.QListView(self.ContainerViews)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.gridLayout_5.addWidget(self.listView, 1, 1, 1, 1)
        self.label_59 = QtGui.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_5.addWidget(self.label_59, 2, 0, 1, 1)
        self.label_60 = QtGui.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_5.addWidget(self.label_60, 3, 0, 1, 1)
        self.tableView = QtGui.QTableView(self.ContainerViews)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.gridLayout_5.addWidget(self.tableView, 3, 1, 1, 1)
        self.label_61 = QtGui.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_5.addWidget(self.label_61, 4, 0, 1, 1)
        self.columnView = QtGui.QColumnView(self.ContainerViews)
        self.columnView.setObjectName(_fromUtf8("columnView"))
        self.gridLayout_5.addWidget(self.columnView, 4, 1, 1, 1)
        self.label_70 = QtGui.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_5.addWidget(self.label_70, 0, 1, 1, 1)
        self.listViewDis = QtGui.QListView(self.ContainerViews)
        self.listViewDis.setEnabled(False)
        self.listViewDis.setObjectName(_fromUtf8("listViewDis"))
        self.gridLayout_5.addWidget(self.listViewDis, 1, 2, 1, 1)
        self.label_80 = QtGui.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_80.setFont(font)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.gridLayout_5.addWidget(self.label_80, 0, 2, 1, 1)
        self.treeViewDis = QtGui.QTreeView(self.ContainerViews)
        self.treeViewDis.setEnabled(False)
        self.treeViewDis.setObjectName(_fromUtf8("treeViewDis"))
        self.gridLayout_5.addWidget(self.treeViewDis, 2, 2, 1, 1)
        self.tableViewDis = QtGui.QTableView(self.ContainerViews)
        self.tableViewDis.setEnabled(False)
        self.tableViewDis.setObjectName(_fromUtf8("tableViewDis"))
        self.gridLayout_5.addWidget(self.tableViewDis, 3, 2, 1, 1)
        self.columnViewDis = QtGui.QColumnView(self.ContainerViews)
        self.columnViewDis.setEnabled(False)
        self.columnViewDis.setObjectName(_fromUtf8("columnViewDis"))
        self.gridLayout_5.addWidget(self.columnViewDis, 4, 2, 1, 1)
        self.tabWidget.addTab(self.ContainerViews, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.label_71 = QtGui.QLabel(self.centralwidget)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.verticalLayout_4.addWidget(self.label_71)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuMenuSub = QtGui.QMenu(self.menuMenu)
        self.menuMenuSub.setObjectName(_fromUtf8("menuMenuSub"))
        self.menuMenuDelayed = QtGui.QMenu(self.menubar)
        self.menuMenuDelayed.setObjectName(_fromUtf8("menuMenuDelayed"))
        self.menuMenuSubDelayed = QtGui.QMenu(self.menuMenuDelayed)
        self.menuMenuSubDelayed.setObjectName(_fromUtf8("menuMenuSubDelayed"))
        self.menuMenuCheckale = QtGui.QMenu(self.menubar)
        self.menuMenuCheckale.setObjectName(_fromUtf8("menuMenuCheckale"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBarDelayed = QtGui.QToolBar(MainWindow)
        self.toolBarDelayed.setObjectName(_fromUtf8("toolBarDelayed"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarDelayed)
        self.toolBarCheckable = QtGui.QToolBar(MainWindow)
        self.toolBarCheckable.setObjectName(_fromUtf8("toolBarCheckable"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBarCheckable)
        self.actionActionA = QtGui.QAction(MainWindow)
        self.actionActionA.setObjectName(_fromUtf8("actionActionA"))
        self.actionActionSubA = QtGui.QAction(MainWindow)
        self.actionActionSubA.setObjectName(_fromUtf8("actionActionSubA"))
        self.actionActionSubB = QtGui.QAction(MainWindow)
        self.actionActionSubB.setObjectName(_fromUtf8("actionActionSubB"))
        self.actionActionDelayedA = QtGui.QAction(MainWindow)
        self.actionActionDelayedA.setObjectName(_fromUtf8("actionActionDelayedA"))
        self.actionActionDelayedSubA = QtGui.QAction(MainWindow)
        self.actionActionDelayedSubA.setObjectName(_fromUtf8("actionActionDelayedSubA"))
        self.actionActionCheckableA = QtGui.QAction(MainWindow)
        self.actionActionCheckableA.setCheckable(True)
        self.actionActionCheckableA.setObjectName(_fromUtf8("actionActionCheckableA"))
        self.actionActionCheckableSubAChecked = QtGui.QAction(MainWindow)
        self.actionActionCheckableSubAChecked.setCheckable(True)
        self.actionActionCheckableSubAChecked.setChecked(True)
        self.actionActionCheckableSubAChecked.setObjectName(_fromUtf8("actionActionCheckableSubAChecked"))
        self.actionActionCheckableSubAUnchecked = QtGui.QAction(MainWindow)
        self.actionActionCheckableSubAUnchecked.setCheckable(True)
        self.actionActionCheckableSubAUnchecked.setObjectName(_fromUtf8("actionActionCheckableSubAUnchecked"))
        self.menuMenuSub.addAction(self.actionActionSubA)
        self.menuMenuSub.addAction(self.actionActionSubB)
        self.menuMenu.addAction(self.actionActionA)
        self.menuMenu.addAction(self.menuMenuSub.menuAction())
        self.menuMenuSubDelayed.addAction(self.actionActionDelayedSubA)
        self.menuMenuDelayed.addAction(self.actionActionDelayedA)
        self.menuMenuDelayed.addAction(self.menuMenuSubDelayed.menuAction())
        self.menuMenuCheckale.addAction(self.actionActionCheckableA)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuMenuDelayed.menuAction())
        self.menubar.addAction(self.menuMenuCheckale.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionActionA)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionActionSubA)
        self.toolBar.addAction(self.actionActionSubB)
        self.toolBarDelayed.addAction(self.actionActionDelayedA)
        self.toolBarDelayed.addSeparator()
        self.toolBarDelayed.addAction(self.actionActionDelayedSubA)
        self.toolBarCheckable.addAction(self.actionActionCheckableA)
        self.toolBarCheckable.addSeparator()
        self.toolBarCheckable.addAction(self.actionActionCheckableSubAChecked)
        self.toolBarCheckable.addAction(self.actionActionCheckableSubAUnchecked)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.toolBoxDis.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidgetDis.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        self.tabWidgetNorth.setCurrentIndex(0)
        self.tabWidgetWest.setCurrentIndex(0)
        self.tabWidgetEast.setCurrentIndex(0)
        self.tabWidgetSouth.setCurrentIndex(0)
        QtCore.QObject.connect(self.toolBox, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), self.toolBoxDis.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.tabWidget.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.groupBoxDis.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label_4.setText(_translate("MainWindow", "Inside GroupBox", None))
        self.toolBoxDis.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.toolBoxDis.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.toolBoxDis.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_93.setText(_translate("MainWindow", "Inside ToolBox Page 1", None))
        self.toolBoxDis.setItemText(self.toolBoxDis.indexOf(self.page_4), _translate("MainWindow", "Page 1", None))
        self.label_94.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_94.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_94.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_94.setText(_translate("MainWindow", "Inside ToolBox Page 2", None))
        self.toolBoxDis.setItemText(self.toolBoxDis.indexOf(self.page_5), _translate("MainWindow", "Page 2", None))
        self.subwindow1Dis.setWindowTitle(_translate("MainWindow", "Subwindow", None))
        self.label_98.setText(_translate("MainWindow", "Inside MDI Area 1", None))
        self.subwindow2Dis.setWindowTitle(_translate("MainWindow", "Subwindow", None))
        self.label_99.setText(_translate("MainWindow", "Inside MDI Area 2 ", None))
        self.subwindow1.setWindowTitle(_translate("MainWindow", "Subwindow", None))
        self.label_28.setText(_translate("MainWindow", "Inside MDI Area 1", None))
        self.subwindow2.setWindowTitle(_translate("MainWindow", "Subwindow", None))
        self.label_40.setText(_translate("MainWindow", "Inside MDI Area 2 ", None))
        self.stackedWidget.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.stackedWidget.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.stackedWidget.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_44.setText(_translate("MainWindow", "Inside Stacked Page 1", None))
        self.label_45.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_45.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_45.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_45.setText(_translate("MainWindow", "Inside Stacked Page 2", None))
        self.stackedWidgetDis.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.stackedWidgetDis.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.stackedWidgetDis.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_95.setText(_translate("MainWindow", "Inside Stacked Page 1", None))
        self.label_96.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_96.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_96.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_96.setText(_translate("MainWindow", "Inside Stacked Page 2", None))
        self.scrollAreaDis.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.scrollAreaDis.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.scrollAreaDis.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_84.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_84.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_84.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_84.setText(_translate("MainWindow", "Inside ScroolArea", None))
        self.label_85.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_85.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_85.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_85.setText(_translate("MainWindow", "ScroolArea ", None))
        self.label_86.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_86.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_86.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_86.setText(_translate("MainWindow", "Inside ScroolArea ", None))
        self.label_87.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_87.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_87.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_87.setText(_translate("MainWindow", "ScroolArea", None))
        self.label_88.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_88.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_88.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_88.setText(_translate("MainWindow", "Inside ScroolArea", None))
        self.label_89.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_89.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_89.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_89.setText(_translate("MainWindow", "ScroolArea", None))
        self.label_90.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_90.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_90.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_90.setText(_translate("MainWindow", "Inside ScroolArea", None))
        self.label_91.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_91.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_91.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_91.setText(_translate("MainWindow", "ScroolArea", None))
        self.label_92.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_92.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_92.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_92.setText(_translate("MainWindow", "Inside ScroolArea", None))
        self.widget.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.widget.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.widget.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_47.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_47.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_47.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_47.setText(_translate("MainWindow", "Inside Widget", None))
        self.label_100.setText(_translate("MainWindow", "Enabled", None))
        self.frameDis.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.frameDis.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.frameDis.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_3.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_3.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_3.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_3.setText(_translate("MainWindow", "Inside Frame", None))
        self.toolBox.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.toolBox.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.toolBox.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_41.setText(_translate("MainWindow", "Inside ToolBox Page 1", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_1), _translate("MainWindow", "Page 1", None))
        self.label_42.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_42.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_42.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_42.setText(_translate("MainWindow", "Inside ToolBox Page 2", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Page 2", None))
        self.frame.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.frame.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.frame.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_2.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_2.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_2.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_2.setText(_translate("MainWindow", "Inside Frame", None))
        self.widgetDis.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.widgetDis.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.widgetDis.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_97.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_97.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_97.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_97.setText(_translate("MainWindow", "Inside Widget", None))
        self.groupBox.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.groupBox.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.groupBox.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label.setText(_translate("MainWindow", "Inside GroupBox", None))
        self.label_101.setText(_translate("MainWindow", "Disabled", None))
        self.label_102.setText(_translate("MainWindow", "GroupBox", None))
        self.label_103.setText(_translate("MainWindow", "ScroolArea", None))
        self.label_104.setText(_translate("MainWindow", "ToolBox", None))
        self.label_105.setText(_translate("MainWindow", "Stacked", None))
        self.label_106.setText(_translate("MainWindow", "Frame", None))
        self.label_107.setText(_translate("MainWindow", "Widget", None))
        self.label_108.setText(_translate("MainWindow", "MDI Area", None))
        self.scrollArea.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.scrollArea.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.scrollArea.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_43.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_43.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_43.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_43.setText(_translate("MainWindow", "Inside ScroolArea", None))
        self.label_63.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_63.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_63.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_63.setText(_translate("MainWindow", "ScroolArea ", None))
        self.label_66.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_66.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_66.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_66.setText(_translate("MainWindow", "Inside ScroolArea ", None))
        self.label_67.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_67.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_67.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_67.setText(_translate("MainWindow", "ScroolArea", None))
        self.label_68.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_68.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_68.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_68.setText(_translate("MainWindow", "Inside ScroolArea", None))
        self.label_46.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_46.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_46.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_46.setText(_translate("MainWindow", "ScroolArea", None))
        self.label_69.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_69.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_69.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_69.setText(_translate("MainWindow", "Inside ScroolArea", None))
        self.label_64.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_64.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_64.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_64.setText(_translate("MainWindow", "ScroolArea", None))
        self.label_65.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_65.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_65.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_65.setText(_translate("MainWindow", "Inside ScroolArea", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ContainerContainers), _translate("MainWindow", "Containers", None))
        self.label_52.setText(_translate("MainWindow", "Inside TabWidget North Closable Tab 1", None))
        self.tabWidgetNorth.setTabText(self.tabWidgetNorth.indexOf(self.tab_7), _translate("MainWindow", "Tab 1", None))
        self.label_48.setText(_translate("MainWindow", "Inside TabWidget North Closable Tab 2", None))
        self.tabWidgetNorth.setTabText(self.tabWidgetNorth.indexOf(self.tab_8), _translate("MainWindow", "Tab 2", None))
        self.label_39.setText(_translate("MainWindow", "Inside TabWidget West Tab 1", None))
        self.tabWidgetWest.setTabText(self.tabWidgetWest.indexOf(self.tab_5), _translate("MainWindow", "Tab 1", None))
        self.label_54.setText(_translate("MainWindow", "Inside TabWidget West Tab 2", None))
        self.tabWidgetWest.setTabText(self.tabWidgetWest.indexOf(self.tab_6), _translate("MainWindow", "Tab 2", None))
        self.label_38.setText(_translate("MainWindow", "Inside TabWidget East Tab 1", None))
        self.tabWidgetEast.setTabText(self.tabWidgetEast.indexOf(self.tab_3), _translate("MainWindow", "Tab 1", None))
        self.label_55.setText(_translate("MainWindow", "Inside TabWidget East Tab 2", None))
        self.tabWidgetEast.setTabText(self.tabWidgetEast.indexOf(self.tab_4), _translate("MainWindow", "Tab 2", None))
        self.label_34.setText(_translate("MainWindow", "Inside TabWidget South Closable Tab 1", None))
        self.tabWidgetSouth.setTabText(self.tabWidgetSouth.indexOf(self.tab), _translate("MainWindow", "Tab 1", None))
        self.label_62.setText(_translate("MainWindow", "Inside TabWidget South Closable Tab 2", None))
        self.tabWidgetSouth.setTabText(self.tabWidgetSouth.indexOf(self.tab_2), _translate("MainWindow", "Tab 2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ContainerContainersTab), _translate("MainWindow", "Containers - Tabs", None))
        self.listWidget.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.listWidget.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.listWidget.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "New Item", None))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "New Item", None))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "New Item", None))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "New Item", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tableWidget.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.tableWidget.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.tableWidget.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "1.23", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Hello", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "1,45", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "Olá", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "12/12/2012", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "Oui", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.treeWidget.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.treeWidget.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.treeWidget.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "New Column", None))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "New Column", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "New Item", None))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "New Subitem", None))
        self.treeWidget.topLevelItem(0).child(0).setText(1, _translate("MainWindow", "Test", None))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "New Subitem", None))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "New Item", None))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "New Subitem", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_58.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_58.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_58.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_58.setText(_translate("MainWindow", "TableWidget", None))
        item = self.tableWidgetDis.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidgetDis.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidgetDis.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidgetDis.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column", None))
        item = self.tableWidgetDis.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column", None))
        __sortingEnabled = self.tableWidgetDis.isSortingEnabled()
        self.tableWidgetDis.setSortingEnabled(False)
        item = self.tableWidgetDis.item(0, 0)
        item.setText(_translate("MainWindow", "1.23", None))
        item = self.tableWidgetDis.item(0, 1)
        item.setText(_translate("MainWindow", "Hello", None))
        item = self.tableWidgetDis.item(1, 0)
        item.setText(_translate("MainWindow", "1,45", None))
        item = self.tableWidgetDis.item(1, 1)
        item.setText(_translate("MainWindow", "Olá", None))
        item = self.tableWidgetDis.item(2, 0)
        item.setText(_translate("MainWindow", "12/12/2012", None))
        item = self.tableWidgetDis.item(2, 1)
        item.setText(_translate("MainWindow", "Oui", None))
        self.tableWidgetDis.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidgetDis.isSortingEnabled()
        self.listWidgetDis.setSortingEnabled(False)
        item = self.listWidgetDis.item(0)
        item.setText(_translate("MainWindow", "New Item", None))
        item = self.listWidgetDis.item(1)
        item.setText(_translate("MainWindow", "New Item", None))
        item = self.listWidgetDis.item(2)
        item.setText(_translate("MainWindow", "New Item", None))
        item = self.listWidgetDis.item(3)
        item.setText(_translate("MainWindow", "New Item", None))
        self.listWidgetDis.setSortingEnabled(__sortingEnabled)
        self.label_57.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_57.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_57.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_57.setText(_translate("MainWindow", "TreeWidget", None))
        self.label_56.setToolTip(_translate("MainWindow", "This is a tool tip", None))
        self.label_56.setStatusTip(_translate("MainWindow", "This is a status tip", None))
        self.label_56.setWhatsThis(_translate("MainWindow", "This is \"what is this\"", None))
        self.label_56.setText(_translate("MainWindow", "ListWidget", None))
        self.treeWidgetDis.setSortingEnabled(True)
        self.treeWidgetDis.headerItem().setText(0, _translate("MainWindow", "New Column", None))
        self.treeWidgetDis.headerItem().setText(1, _translate("MainWindow", "New Column", None))
        __sortingEnabled = self.treeWidgetDis.isSortingEnabled()
        self.treeWidgetDis.setSortingEnabled(False)
        self.treeWidgetDis.topLevelItem(0).setText(0, _translate("MainWindow", "New Item", None))
        self.treeWidgetDis.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "New Subitem", None))
        self.treeWidgetDis.topLevelItem(0).child(0).setText(1, _translate("MainWindow", "Test", None))
        self.treeWidgetDis.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "New Subitem", None))
        self.treeWidgetDis.topLevelItem(1).setText(0, _translate("MainWindow", "New Item", None))
        self.treeWidgetDis.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "New Subitem", None))
        self.treeWidgetDis.setSortingEnabled(__sortingEnabled)
        self.label_81.setText(_translate("MainWindow", "Enabled", None))
        self.label_82.setText(_translate("MainWindow", "Disabled", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ContainerWidgets), _translate("MainWindow", "Widgets", None))
        self.label_27.setText(_translate("MainWindow", "ListView", None))
        self.label_59.setText(_translate("MainWindow", "TreeView", None))
        self.label_60.setText(_translate("MainWindow", "TableView", None))
        self.label_61.setText(_translate("MainWindow", "ColunmView", None))
        self.label_70.setText(_translate("MainWindow", "Enabled", None))
        self.label_80.setText(_translate("MainWindow", "Disabled", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ContainerViews), _translate("MainWindow", "Views", None))
        self.label_71.setText(_translate("MainWindow", "Inside CentralWidget", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.menuMenuSub.setTitle(_translate("MainWindow", "Menu Sub", None))
        self.menuMenuDelayed.setTitle(_translate("MainWindow", "Menu Delayed", None))
        self.menuMenuSubDelayed.setTitle(_translate("MainWindow", "Menu Sub Delayed", None))
        self.menuMenuCheckale.setTitle(_translate("MainWindow", "Menu Checkable", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About QDarkStyle", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBarDelayed.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBarCheckable.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.actionActionA.setText(_translate("MainWindow", "Action A", None))
        self.actionActionSubA.setText(_translate("MainWindow", "Action A Sub", None))
        self.actionActionSubA.setToolTip(_translate("MainWindow", "Action A Sub", None))
        self.actionActionSubB.setText(_translate("MainWindow", "Action B Sub", None))
        self.actionActionDelayedA.setText(_translate("MainWindow", "Action Delayed A", None))
        self.actionActionDelayedA.setToolTip(_translate("MainWindow", "Action Delayed A", None))
        self.actionActionDelayedSubA.setText(_translate("MainWindow", "Action Delayed Sub A", None))
        self.actionActionDelayedSubA.setToolTip(_translate("MainWindow", "Action Delayed Sub A", None))
        self.actionActionCheckableA.setText(_translate("MainWindow", "Action Checkable A", None))
        self.actionActionCheckableA.setToolTip(_translate("MainWindow", "Action Checkable A", None))
        self.actionActionCheckableSubAChecked.setText(_translate("MainWindow", "Action Checkable Sub A Checked", None))
        self.actionActionCheckableSubAChecked.setToolTip(_translate("MainWindow", "Action Checkable Sub A Checked", None))
        self.actionActionCheckableSubAUnchecked.setText(_translate("MainWindow", "Action Checkable Sub A Unchecked", None))
        self.actionActionCheckableSubAUnchecked.setToolTip(_translate("MainWindow", "Action Checkable Sub A Unchecked", None))

