# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw_views_widgets_containers.ui'
#
# Created: Tue Feb  6 10:43:55 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 705)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.ContainerContainers = QtGui.QWidget()
        self.ContainerContainers.setObjectName("ContainerContainers")
        self.gridLayout_29 = QtGui.QGridLayout(self.ContainerContainers)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.groupBoxDis = QtGui.QGroupBox(self.ContainerContainers)
        self.groupBoxDis.setEnabled(False)
        self.groupBoxDis.setObjectName("groupBoxDis")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBoxDis)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(self.groupBoxDis)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout_29.addWidget(self.groupBoxDis, 1, 2, 1, 1)
        self.toolBoxDis = QtGui.QToolBox(self.ContainerContainers)
        self.toolBoxDis.setEnabled(False)
        self.toolBoxDis.setObjectName("toolBoxDis")
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 196, 73))
        self.page_4.setObjectName("page_4")
        self.gridLayout_23 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_93 = QtGui.QLabel(self.page_4)
        self.label_93.setObjectName("label_93")
        self.gridLayout_23.addWidget(self.label_93, 2, 0, 1, 1)
        self.toolBoxDis.addItem(self.page_4, "")
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 163, 38))
        self.page_5.setObjectName("page_5")
        self.gridLayout_24 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_94 = QtGui.QLabel(self.page_5)
        self.label_94.setObjectName("label_94")
        self.gridLayout_24.addWidget(self.label_94, 0, 0, 1, 1)
        self.toolBoxDis.addItem(self.page_5, "")
        self.gridLayout_29.addWidget(self.toolBoxDis, 3, 2, 1, 1)
        self.mdiAreaDis = QtGui.QMdiArea(self.ContainerContainers)
        self.mdiAreaDis.setEnabled(False)
        self.mdiAreaDis.setObjectName("mdiAreaDis")
        self.subwindow1Dis = QtGui.QWidget()
        self.subwindow1Dis.setObjectName("subwindow1Dis")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.subwindow1Dis)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_98 = QtGui.QLabel(self.subwindow1Dis)
        self.label_98.setObjectName("label_98")
        self.verticalLayout_7.addWidget(self.label_98)
        self.subwindow2Dis = QtGui.QWidget()
        self.subwindow2Dis.setObjectName("subwindow2Dis")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.subwindow2Dis)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_99 = QtGui.QLabel(self.subwindow2Dis)
        self.label_99.setObjectName("label_99")
        self.verticalLayout_8.addWidget(self.label_99)
        self.gridLayout_29.addWidget(self.mdiAreaDis, 7, 2, 1, 1)
        self.mdiArea = QtGui.QMdiArea(self.ContainerContainers)
        self.mdiArea.setObjectName("mdiArea")
        self.subwindow1 = QtGui.QWidget()
        self.subwindow1.setObjectName("subwindow1")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.subwindow1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_28 = QtGui.QLabel(self.subwindow1)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_5.addWidget(self.label_28)
        self.subwindow2 = QtGui.QWidget()
        self.subwindow2.setObjectName("subwindow2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.subwindow2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_40 = QtGui.QLabel(self.subwindow2)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_6.addWidget(self.label_40)
        self.gridLayout_29.addWidget(self.mdiArea, 7, 1, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.ContainerContainers)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtGui.QWidget()
        self.page1.setObjectName("page1")
        self.gridLayout_12 = QtGui.QGridLayout(self.page1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_44 = QtGui.QLabel(self.page1)
        self.label_44.setObjectName("label_44")
        self.gridLayout_12.addWidget(self.label_44, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtGui.QWidget()
        self.page2.setObjectName("page2")
        self.gridLayout_13 = QtGui.QGridLayout(self.page2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_45 = QtGui.QLabel(self.page2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_13.addWidget(self.label_45, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page2)
        self.gridLayout_29.addWidget(self.stackedWidget, 4, 1, 1, 1)
        self.stackedWidgetDis = QtGui.QStackedWidget(self.ContainerContainers)
        self.stackedWidgetDis.setEnabled(False)
        self.stackedWidgetDis.setObjectName("stackedWidgetDis")
        self.page1Dis = QtGui.QWidget()
        self.page1Dis.setObjectName("page1Dis")
        self.gridLayout_26 = QtGui.QGridLayout(self.page1Dis)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_95 = QtGui.QLabel(self.page1Dis)
        self.label_95.setObjectName("label_95")
        self.gridLayout_26.addWidget(self.label_95, 0, 0, 1, 1)
        self.stackedWidgetDis.addWidget(self.page1Dis)
        self.page2Dis = QtGui.QWidget()
        self.page2Dis.setObjectName("page2Dis")
        self.gridLayout_27 = QtGui.QGridLayout(self.page2Dis)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_96 = QtGui.QLabel(self.page2Dis)
        self.label_96.setObjectName("label_96")
        self.gridLayout_27.addWidget(self.label_96, 0, 0, 1, 1)
        self.stackedWidgetDis.addWidget(self.page2Dis)
        self.gridLayout_29.addWidget(self.stackedWidgetDis, 4, 2, 1, 1)
        self.scrollAreaDis = QtGui.QScrollArea(self.ContainerContainers)
        self.scrollAreaDis.setEnabled(False)
        self.scrollAreaDis.setWidgetResizable(True)
        self.scrollAreaDis.setObjectName("scrollAreaDis")
        self.scrollAreaWidgetContentsDis = QtGui.QWidget()
        self.scrollAreaWidgetContentsDis.setGeometry(QtCore.QRect(0, 0, 181, 246))
        self.scrollAreaWidgetContentsDis.setObjectName("scrollAreaWidgetContentsDis")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContentsDis)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_84 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_3.addWidget(self.label_84)
        self.label_85 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_3.addWidget(self.label_85)
        self.label_86 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_3.addWidget(self.label_86)
        self.label_87 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_87.setObjectName("label_87")
        self.verticalLayout_3.addWidget(self.label_87)
        self.label_88 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_88.setObjectName("label_88")
        self.verticalLayout_3.addWidget(self.label_88)
        self.label_89 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_89.setObjectName("label_89")
        self.verticalLayout_3.addWidget(self.label_89)
        self.label_90 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_90.setObjectName("label_90")
        self.verticalLayout_3.addWidget(self.label_90)
        self.label_91 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_91.setObjectName("label_91")
        self.verticalLayout_3.addWidget(self.label_91)
        self.label_92 = QtGui.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_92.setObjectName("label_92")
        self.verticalLayout_3.addWidget(self.label_92)
        self.scrollAreaDis.setWidget(self.scrollAreaWidgetContentsDis)
        self.gridLayout_29.addWidget(self.scrollAreaDis, 2, 2, 1, 1)
        self.widget = QtGui.QWidget(self.ContainerContainers)
        self.widget.setObjectName("widget")
        self.gridLayout_17 = QtGui.QGridLayout(self.widget)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_47 = QtGui.QLabel(self.widget)
        self.label_47.setObjectName("label_47")
        self.gridLayout_17.addWidget(self.label_47, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.widget, 6, 1, 1, 1)
        self.label_100 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_100.setFont(font)
        self.label_100.setObjectName("label_100")
        self.gridLayout_29.addWidget(self.label_100, 0, 1, 1, 1)
        self.frameDis = QtGui.QFrame(self.ContainerContainers)
        self.frameDis.setEnabled(False)
        self.frameDis.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameDis.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDis.setObjectName("frameDis")
        self.gridLayout_25 = QtGui.QGridLayout(self.frameDis)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_3 = QtGui.QLabel(self.frameDis)
        self.label_3.setObjectName("label_3")
        self.gridLayout_25.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.frameDis, 5, 2, 1, 1)
        self.toolBox = QtGui.QToolBox(self.ContainerContainers)
        self.toolBox.setObjectName("toolBox")
        self.page_1 = QtGui.QWidget()
        self.page_1.setGeometry(QtCore.QRect(0, 0, 196, 73))
        self.page_1.setObjectName("page_1")
        self.gridLayout_14 = QtGui.QGridLayout(self.page_1)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_41 = QtGui.QLabel(self.page_1)
        self.label_41.setObjectName("label_41")
        self.gridLayout_14.addWidget(self.label_41, 2, 0, 1, 1)
        self.toolBox.addItem(self.page_1, "")
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 163, 38))
        self.page_2.setObjectName("page_2")
        self.gridLayout_15 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_42 = QtGui.QLabel(self.page_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_15.addWidget(self.label_42, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_2, "")
        self.gridLayout_29.addWidget(self.toolBox, 3, 1, 1, 1)
        self.frame = QtGui.QFrame(self.ContainerContainers)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_16 = QtGui.QGridLayout(self.frame)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_16.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.frame, 5, 1, 1, 1)
        self.widgetDis = QtGui.QWidget(self.ContainerContainers)
        self.widgetDis.setEnabled(False)
        self.widgetDis.setObjectName("widgetDis")
        self.gridLayout_28 = QtGui.QGridLayout(self.widgetDis)
        self.gridLayout_28.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.label_97 = QtGui.QLabel(self.widgetDis)
        self.label_97.setObjectName("label_97")
        self.gridLayout_28.addWidget(self.label_97, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.widgetDis, 6, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.ContainerContainers)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.groupBox, 1, 1, 1, 1)
        self.label_101 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_101.setFont(font)
        self.label_101.setObjectName("label_101")
        self.gridLayout_29.addWidget(self.label_101, 0, 2, 1, 1)
        self.label_102 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_102.setFont(font)
        self.label_102.setObjectName("label_102")
        self.gridLayout_29.addWidget(self.label_102, 1, 0, 1, 1)
        self.label_103 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_103.setFont(font)
        self.label_103.setObjectName("label_103")
        self.gridLayout_29.addWidget(self.label_103, 2, 0, 1, 1)
        self.label_104 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_104.setFont(font)
        self.label_104.setObjectName("label_104")
        self.gridLayout_29.addWidget(self.label_104, 3, 0, 1, 1)
        self.label_105 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_105.setFont(font)
        self.label_105.setObjectName("label_105")
        self.gridLayout_29.addWidget(self.label_105, 4, 0, 1, 1)
        self.label_106 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_106.setFont(font)
        self.label_106.setObjectName("label_106")
        self.gridLayout_29.addWidget(self.label_106, 5, 0, 1, 1)
        self.label_107 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_107.setFont(font)
        self.label_107.setObjectName("label_107")
        self.gridLayout_29.addWidget(self.label_107, 6, 0, 1, 1)
        self.label_108 = QtGui.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_108.setFont(font)
        self.label_108.setObjectName("label_108")
        self.gridLayout_29.addWidget(self.label_108, 7, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.ContainerContainers)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 181, 246))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_43 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_2.addWidget(self.label_43)
        self.label_63 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_2.addWidget(self.label_63)
        self.label_66 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_2.addWidget(self.label_66)
        self.label_67 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_2.addWidget(self.label_67)
        self.label_68 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_68.setObjectName("label_68")
        self.verticalLayout_2.addWidget(self.label_68)
        self.label_46 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_2.addWidget(self.label_46)
        self.label_69 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_2.addWidget(self.label_69)
        self.label_64 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_2.addWidget(self.label_64)
        self.label_65 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_2.addWidget(self.label_65)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_29.addWidget(self.scrollArea, 2, 1, 1, 1)
        self.tabWidget.addTab(self.ContainerContainers, "")
        self.ContainerContainersTab = QtGui.QWidget()
        self.ContainerContainersTab.setObjectName("ContainerContainersTab")
        self.gridLayout_22 = QtGui.QGridLayout(self.ContainerContainersTab)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.tabWidgetNorth = QtGui.QTabWidget(self.ContainerContainersTab)
        self.tabWidgetNorth.setDocumentMode(False)
        self.tabWidgetNorth.setTabsClosable(True)
        self.tabWidgetNorth.setObjectName("tabWidgetNorth")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_52 = QtGui.QLabel(self.tab_7)
        self.label_52.setObjectName("label_52")
        self.gridLayout_8.addWidget(self.label_52, 0, 0, 1, 1)
        self.tabWidgetNorth.addTab(self.tab_7, "")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_48 = QtGui.QLabel(self.tab_8)
        self.label_48.setObjectName("label_48")
        self.gridLayout_4.addWidget(self.label_48, 0, 0, 1, 1)
        self.tabWidgetNorth.addTab(self.tab_8, "")
        self.gridLayout_22.addWidget(self.tabWidgetNorth, 0, 0, 1, 1)
        self.tabWidgetWest = QtGui.QTabWidget(self.ContainerContainersTab)
        self.tabWidgetWest.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidgetWest.setObjectName("tabWidgetWest")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_39 = QtGui.QLabel(self.tab_5)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 0, 0, 1, 1)
        self.tabWidgetWest.addTab(self.tab_5, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_54 = QtGui.QLabel(self.tab_6)
        self.label_54.setObjectName("label_54")
        self.gridLayout_9.addWidget(self.label_54, 0, 0, 1, 1)
        self.tabWidgetWest.addTab(self.tab_6, "")
        self.gridLayout_22.addWidget(self.tabWidgetWest, 1, 0, 1, 1)
        self.tabWidgetEast = QtGui.QTabWidget(self.ContainerContainersTab)
        self.tabWidgetEast.setTabPosition(QtGui.QTabWidget.East)
        self.tabWidgetEast.setObjectName("tabWidgetEast")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_38 = QtGui.QLabel(self.tab_3)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 0, 0, 1, 1)
        self.tabWidgetEast.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_55 = QtGui.QLabel(self.tab_4)
        self.label_55.setObjectName("label_55")
        self.gridLayout_11.addWidget(self.label_55, 0, 0, 1, 1)
        self.tabWidgetEast.addTab(self.tab_4, "")
        self.gridLayout_22.addWidget(self.tabWidgetEast, 2, 0, 1, 1)
        self.tabWidgetSouth = QtGui.QTabWidget(self.ContainerContainersTab)
        self.tabWidgetSouth.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidgetSouth.setTabsClosable(True)
        self.tabWidgetSouth.setObjectName("tabWidgetSouth")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_34 = QtGui.QLabel(self.tab)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 0, 0, 1, 1)
        self.tabWidgetSouth.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_18 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_62 = QtGui.QLabel(self.tab_2)
        self.label_62.setObjectName("label_62")
        self.gridLayout_18.addWidget(self.label_62, 0, 0, 1, 1)
        self.tabWidgetSouth.addTab(self.tab_2, "")
        self.gridLayout_22.addWidget(self.tabWidgetSouth, 3, 0, 1, 1)
        self.tabWidget.addTab(self.ContainerContainersTab, "")
        self.ContainerWidgets = QtGui.QWidget()
        self.ContainerWidgets.setObjectName("ContainerWidgets")
        self.gridLayout_7 = QtGui.QGridLayout(self.ContainerWidgets)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.listWidget = QtGui.QListWidget(self.ContainerWidgets)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget.setObjectName("listWidget")
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        self.gridLayout_7.addWidget(self.listWidget, 1, 2, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.ContainerWidgets)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        self.gridLayout_7.addWidget(self.tableWidget, 3, 2, 1, 1)
        self.treeWidget = QtGui.QTreeWidget(self.ContainerWidgets)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.treeWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.gridLayout_7.addWidget(self.treeWidget, 2, 2, 1, 1)
        self.label_58 = QtGui.QLabel(self.ContainerWidgets)
        self.label_58.setMinimumSize(QtCore.QSize(0, 0))
        self.label_58.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_7.addWidget(self.label_58, 3, 1, 1, 1)
        self.tableWidgetDis = QtGui.QTableWidget(self.ContainerWidgets)
        self.tableWidgetDis.setEnabled(False)
        self.tableWidgetDis.setObjectName("tableWidgetDis")
        self.tableWidgetDis.setColumnCount(2)
        self.tableWidgetDis.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDis.setItem(2, 1, item)
        self.gridLayout_7.addWidget(self.tableWidgetDis, 3, 3, 1, 1)
        self.listWidgetDis = QtGui.QListWidget(self.ContainerWidgets)
        self.listWidgetDis.setEnabled(False)
        self.listWidgetDis.setObjectName("listWidgetDis")
        QtGui.QListWidgetItem(self.listWidgetDis)
        QtGui.QListWidgetItem(self.listWidgetDis)
        QtGui.QListWidgetItem(self.listWidgetDis)
        QtGui.QListWidgetItem(self.listWidgetDis)
        self.gridLayout_7.addWidget(self.listWidgetDis, 1, 3, 1, 1)
        self.label_57 = QtGui.QLabel(self.ContainerWidgets)
        self.label_57.setMinimumSize(QtCore.QSize(0, 0))
        self.label_57.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_7.addWidget(self.label_57, 2, 1, 1, 1)
        self.label_56 = QtGui.QLabel(self.ContainerWidgets)
        self.label_56.setMinimumSize(QtCore.QSize(0, 0))
        self.label_56.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_7.addWidget(self.label_56, 1, 1, 1, 1)
        self.treeWidgetDis = QtGui.QTreeWidget(self.ContainerWidgets)
        self.treeWidgetDis.setEnabled(False)
        self.treeWidgetDis.setObjectName("treeWidgetDis")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidgetDis)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidgetDis)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.gridLayout_7.addWidget(self.treeWidgetDis, 2, 3, 1, 1)
        self.label_81 = QtGui.QLabel(self.ContainerWidgets)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.gridLayout_7.addWidget(self.label_81, 0, 2, 1, 1)
        self.label_82 = QtGui.QLabel(self.ContainerWidgets)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.gridLayout_7.addWidget(self.label_82, 0, 3, 1, 1)
        self.tabWidget.addTab(self.ContainerWidgets, "")
        self.ContainerViews = QtGui.QWidget()
        self.ContainerViews.setObjectName("ContainerViews")
        self.gridLayout_5 = QtGui.QGridLayout(self.ContainerViews)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.treeView = QtGui.QTreeView(self.ContainerViews)
        self.treeView.setObjectName("treeView")
        self.gridLayout_5.addWidget(self.treeView, 2, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 1, 0, 1, 1)
        self.listView = QtGui.QListView(self.ContainerViews)
        self.listView.setObjectName("listView")
        self.gridLayout_5.addWidget(self.listView, 1, 1, 1, 1)
        self.label_59 = QtGui.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.gridLayout_5.addWidget(self.label_59, 2, 0, 1, 1)
        self.label_60 = QtGui.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_5.addWidget(self.label_60, 3, 0, 1, 1)
        self.tableView = QtGui.QTableView(self.ContainerViews)
        self.tableView.setObjectName("tableView")
        self.gridLayout_5.addWidget(self.tableView, 3, 1, 1, 1)
        self.label_61 = QtGui.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.gridLayout_5.addWidget(self.label_61, 4, 0, 1, 1)
        self.columnView = QtGui.QColumnView(self.ContainerViews)
        self.columnView.setObjectName("columnView")
        self.gridLayout_5.addWidget(self.columnView, 4, 1, 1, 1)
        self.label_70 = QtGui.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.gridLayout_5.addWidget(self.label_70, 0, 1, 1, 1)
        self.listViewDis = QtGui.QListView(self.ContainerViews)
        self.listViewDis.setEnabled(False)
        self.listViewDis.setObjectName("listViewDis")
        self.gridLayout_5.addWidget(self.listViewDis, 1, 2, 1, 1)
        self.label_80 = QtGui.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.gridLayout_5.addWidget(self.label_80, 0, 2, 1, 1)
        self.treeViewDis = QtGui.QTreeView(self.ContainerViews)
        self.treeViewDis.setEnabled(False)
        self.treeViewDis.setObjectName("treeViewDis")
        self.gridLayout_5.addWidget(self.treeViewDis, 2, 2, 1, 1)
        self.tableViewDis = QtGui.QTableView(self.ContainerViews)
        self.tableViewDis.setEnabled(False)
        self.tableViewDis.setObjectName("tableViewDis")
        self.gridLayout_5.addWidget(self.tableViewDis, 3, 2, 1, 1)
        self.columnViewDis = QtGui.QColumnView(self.ContainerViews)
        self.columnViewDis.setEnabled(False)
        self.columnViewDis.setObjectName("columnViewDis")
        self.gridLayout_5.addWidget(self.columnViewDis, 4, 2, 1, 1)
        self.tabWidget.addTab(self.ContainerViews, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.label_71 = QtGui.QLabel(self.centralwidget)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.verticalLayout_4.addWidget(self.label_71)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 28))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuMenuSub = QtGui.QMenu(self.menuMenu)
        self.menuMenuSub.setObjectName("menuMenuSub")
        self.menuMenuDelayed = QtGui.QMenu(self.menubar)
        self.menuMenuDelayed.setObjectName("menuMenuDelayed")
        self.menuMenuSubDelayed = QtGui.QMenu(self.menuMenuDelayed)
        self.menuMenuSubDelayed.setObjectName("menuMenuSubDelayed")
        self.menuMenuCheckale = QtGui.QMenu(self.menubar)
        self.menuMenuCheckale.setObjectName("menuMenuCheckale")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBarDelayed = QtGui.QToolBar(MainWindow)
        self.toolBarDelayed.setObjectName("toolBarDelayed")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarDelayed)
        self.toolBarCheckable = QtGui.QToolBar(MainWindow)
        self.toolBarCheckable.setObjectName("toolBarCheckable")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBarCheckable)
        self.actionActionA = QtGui.QAction(MainWindow)
        self.actionActionA.setObjectName("actionActionA")
        self.actionActionSubA = QtGui.QAction(MainWindow)
        self.actionActionSubA.setObjectName("actionActionSubA")
        self.actionActionSubB = QtGui.QAction(MainWindow)
        self.actionActionSubB.setObjectName("actionActionSubB")
        self.actionActionDelayedA = QtGui.QAction(MainWindow)
        self.actionActionDelayedA.setObjectName("actionActionDelayedA")
        self.actionActionDelayedSubA = QtGui.QAction(MainWindow)
        self.actionActionDelayedSubA.setObjectName("actionActionDelayedSubA")
        self.actionActionCheckableA = QtGui.QAction(MainWindow)
        self.actionActionCheckableA.setCheckable(True)
        self.actionActionCheckableA.setObjectName("actionActionCheckableA")
        self.actionActionCheckableSubAChecked = QtGui.QAction(MainWindow)
        self.actionActionCheckableSubAChecked.setCheckable(True)
        self.actionActionCheckableSubAChecked.setChecked(True)
        self.actionActionCheckableSubAChecked.setObjectName("actionActionCheckableSubAChecked")
        self.actionActionCheckableSubAUnchecked = QtGui.QAction(MainWindow)
        self.actionActionCheckableSubAUnchecked.setCheckable(True)
        self.actionActionCheckableSubAUnchecked.setObjectName("actionActionCheckableSubAUnchecked")
        self.menuMenuSub.addAction(self.actionActionSubA)
        self.menuMenuSub.addAction(self.actionActionSubB)
        self.menuMenu.addAction(self.actionActionA)
        self.menuMenu.addAction(self.menuMenuSub.menuAction())
        self.menuMenuSubDelayed.addAction(self.actionActionDelayedSubA)
        self.menuMenuDelayed.addAction(self.actionActionDelayedA)
        self.menuMenuDelayed.addAction(self.menuMenuSubDelayed.menuAction())
        self.menuMenuCheckale.addAction(self.actionActionCheckableA)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuMenuDelayed.menuAction())
        self.menubar.addAction(self.menuMenuCheckale.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionActionA)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionActionSubA)
        self.toolBar.addAction(self.actionActionSubB)
        self.toolBarDelayed.addAction(self.actionActionDelayedA)
        self.toolBarDelayed.addSeparator()
        self.toolBarDelayed.addAction(self.actionActionDelayedSubA)
        self.toolBarCheckable.addAction(self.actionActionCheckableA)
        self.toolBarCheckable.addSeparator()
        self.toolBarCheckable.addAction(self.actionActionCheckableSubAChecked)
        self.toolBarCheckable.addAction(self.actionActionCheckableSubAUnchecked)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.toolBoxDis.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidgetDis.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        self.tabWidgetNorth.setCurrentIndex(0)
        self.tabWidgetWest.setCurrentIndex(0)
        self.tabWidgetEast.setCurrentIndex(0)
        self.tabWidgetSouth.setCurrentIndex(0)
        QtCore.QObject.connect(self.toolBox, QtCore.SIGNAL("currentChanged(int)"), self.toolBoxDis.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxDis.setTitle(QtGui.QApplication.translate("MainWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Inside GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBoxDis.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBoxDis.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBoxDis.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_93.setText(QtGui.QApplication.translate("MainWindow", "Inside ToolBox Page 1", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBoxDis.setItemText(self.toolBoxDis.indexOf(self.page_4), QtGui.QApplication.translate("MainWindow", "Page 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_94.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_94.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_94.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_94.setText(QtGui.QApplication.translate("MainWindow", "Inside ToolBox Page 2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBoxDis.setItemText(self.toolBoxDis.indexOf(self.page_5), QtGui.QApplication.translate("MainWindow", "Page 2", None, QtGui.QApplication.UnicodeUTF8))
        self.subwindow1Dis.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Subwindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_98.setText(QtGui.QApplication.translate("MainWindow", "Inside MDI Area 1", None, QtGui.QApplication.UnicodeUTF8))
        self.subwindow2Dis.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Subwindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_99.setText(QtGui.QApplication.translate("MainWindow", "Inside MDI Area 2 ", None, QtGui.QApplication.UnicodeUTF8))
        self.subwindow1.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Subwindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Inside MDI Area 1", None, QtGui.QApplication.UnicodeUTF8))
        self.subwindow2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Subwindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Inside MDI Area 2 ", None, QtGui.QApplication.UnicodeUTF8))
        self.stackedWidget.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.stackedWidget.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.stackedWidget.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "Inside Stacked Page 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "Inside Stacked Page 2", None, QtGui.QApplication.UnicodeUTF8))
        self.stackedWidgetDis.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.stackedWidgetDis.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.stackedWidgetDis.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_95.setText(QtGui.QApplication.translate("MainWindow", "Inside Stacked Page 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_96.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_96.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_96.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_96.setText(QtGui.QApplication.translate("MainWindow", "Inside Stacked Page 2", None, QtGui.QApplication.UnicodeUTF8))
        self.scrollAreaDis.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.scrollAreaDis.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.scrollAreaDis.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_84.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_84.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_84.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_84.setText(QtGui.QApplication.translate("MainWindow", "Inside ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.label_85.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_85.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_85.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_85.setText(QtGui.QApplication.translate("MainWindow", "ScroolArea ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_86.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_86.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_86.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_86.setText(QtGui.QApplication.translate("MainWindow", "Inside ScroolArea ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_87.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_87.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_87.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_87.setText(QtGui.QApplication.translate("MainWindow", "ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.label_88.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_88.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_88.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_88.setText(QtGui.QApplication.translate("MainWindow", "Inside ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.label_89.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_89.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_89.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_89.setText(QtGui.QApplication.translate("MainWindow", "ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.label_90.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_90.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_90.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_90.setText(QtGui.QApplication.translate("MainWindow", "Inside ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.label_91.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_91.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_91.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_91.setText(QtGui.QApplication.translate("MainWindow", "ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.label_92.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_92.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_92.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_92.setText(QtGui.QApplication.translate("MainWindow", "Inside ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.widget.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.widget.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.widget.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("MainWindow", "Inside Widget", None, QtGui.QApplication.UnicodeUTF8))
        self.label_100.setText(QtGui.QApplication.translate("MainWindow", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.frameDis.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.frameDis.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.frameDis.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Inside Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Inside ToolBox Page 1", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_1), QtGui.QApplication.translate("MainWindow", "Page 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "Inside ToolBox Page 2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("MainWindow", "Page 2", None, QtGui.QApplication.UnicodeUTF8))
        self.frame.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.frame.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.frame.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Inside Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetDis.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetDis.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetDis.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_97.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_97.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_97.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_97.setText(QtGui.QApplication.translate("MainWindow", "Inside Widget", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Inside GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.label_101.setText(QtGui.QApplication.translate("MainWindow", "Disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.label_102.setText(QtGui.QApplication.translate("MainWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.label_103.setText(QtGui.QApplication.translate("MainWindow", "ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.label_104.setText(QtGui.QApplication.translate("MainWindow", "ToolBox", None, QtGui.QApplication.UnicodeUTF8))
        self.label_105.setText(QtGui.QApplication.translate("MainWindow", "Stacked", None, QtGui.QApplication.UnicodeUTF8))
        self.label_106.setText(QtGui.QApplication.translate("MainWindow", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_107.setText(QtGui.QApplication.translate("MainWindow", "Widget", None, QtGui.QApplication.UnicodeUTF8))
        self.label_108.setText(QtGui.QApplication.translate("MainWindow", "MDI Area", None, QtGui.QApplication.UnicodeUTF8))
        self.scrollArea.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.scrollArea.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.scrollArea.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "Inside ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("MainWindow", "ScroolArea ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("MainWindow", "Inside ScroolArea ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("MainWindow", "ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("MainWindow", "Inside ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("MainWindow", "Inside ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("MainWindow", "ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setText(QtGui.QApplication.translate("MainWindow", "Inside ScroolArea", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ContainerContainers), QtGui.QApplication.translate("MainWindow", "Containers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("MainWindow", "Inside TabWidget North Closable Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetNorth.setTabText(self.tabWidgetNorth.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("MainWindow", "Inside TabWidget North Closable Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetNorth.setTabText(self.tabWidgetNorth.indexOf(self.tab_8), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "Inside TabWidget West Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetWest.setTabText(self.tabWidgetWest.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("MainWindow", "Inside TabWidget West Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetWest.setTabText(self.tabWidgetWest.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Inside TabWidget East Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetEast.setTabText(self.tabWidgetEast.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("MainWindow", "Inside TabWidget East Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetEast.setTabText(self.tabWidgetEast.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Inside TabWidget South Closable Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetSouth.setTabText(self.tabWidgetSouth.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("MainWindow", "Inside TabWidget South Closable Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetSouth.setTabText(self.tabWidgetSouth.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ContainerContainersTab), QtGui.QApplication.translate("MainWindow", "Containers - Tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(1).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(2).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(3).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tableWidget.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "1.23", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(0, 1).setText(QtGui.QApplication.translate("MainWindow", "Hello", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(1, 0).setText(QtGui.QApplication.translate("MainWindow", "1,45", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(1, 1).setText(QtGui.QApplication.translate("MainWindow", "Olá", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(2, 0).setText(QtGui.QApplication.translate("MainWindow", "12/12/2012", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(2, 1).setText(QtGui.QApplication.translate("MainWindow", "Oui", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.treeWidget.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "New Subitem", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(0).child(0).setText(1, QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "New Subitem", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "New Subitem", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_58.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MainWindow", "TableWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetDis.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetDis.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetDis.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetDis.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetDis.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidgetDis.isSortingEnabled()
        self.tableWidgetDis.setSortingEnabled(False)
        self.tableWidgetDis.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "1.23", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetDis.item(0, 1).setText(QtGui.QApplication.translate("MainWindow", "Hello", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetDis.item(1, 0).setText(QtGui.QApplication.translate("MainWindow", "1,45", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetDis.item(1, 1).setText(QtGui.QApplication.translate("MainWindow", "Olá", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetDis.item(2, 0).setText(QtGui.QApplication.translate("MainWindow", "12/12/2012", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetDis.item(2, 1).setText(QtGui.QApplication.translate("MainWindow", "Oui", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetDis.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidgetDis.isSortingEnabled()
        self.listWidgetDis.setSortingEnabled(False)
        self.listWidgetDis.item(0).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetDis.item(1).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetDis.item(2).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetDis.item(3).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetDis.setSortingEnabled(__sortingEnabled)
        self.label_57.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("MainWindow", "TreeWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setToolTip(QtGui.QApplication.translate("MainWindow", "This is a tool tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setStatusTip(QtGui.QApplication.translate("MainWindow", "This is a status tip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setWhatsThis(QtGui.QApplication.translate("MainWindow", "This is \"what is this\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("MainWindow", "ListWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDis.setSortingEnabled(True)
        self.treeWidgetDis.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDis.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidgetDis.isSortingEnabled()
        self.treeWidgetDis.setSortingEnabled(False)
        self.treeWidgetDis.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDis.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "New Subitem", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDis.topLevelItem(0).child(0).setText(1, QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDis.topLevelItem(0).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "New Subitem", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDis.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDis.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "New Subitem", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDis.setSortingEnabled(__sortingEnabled)
        self.label_81.setText(QtGui.QApplication.translate("MainWindow", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.label_82.setText(QtGui.QApplication.translate("MainWindow", "Disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ContainerWidgets), QtGui.QApplication.translate("MainWindow", "Widgets", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "ListView", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("MainWindow", "TreeView", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("MainWindow", "TableView", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("MainWindow", "ColunmView", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("MainWindow", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.label_80.setText(QtGui.QApplication.translate("MainWindow", "Disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ContainerViews), QtGui.QApplication.translate("MainWindow", "Views", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("MainWindow", "Inside CentralWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenuSub.setTitle(QtGui.QApplication.translate("MainWindow", "Menu Sub", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenuDelayed.setTitle(QtGui.QApplication.translate("MainWindow", "Menu Delayed", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenuSubDelayed.setTitle(QtGui.QApplication.translate("MainWindow", "Menu Sub Delayed", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenuCheckale.setTitle(QtGui.QApplication.translate("MainWindow", "Menu Checkable", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About QDarkStyle", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarDelayed.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarCheckable.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionA.setText(QtGui.QApplication.translate("MainWindow", "Action A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionSubA.setText(QtGui.QApplication.translate("MainWindow", "Action A Sub", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionSubA.setToolTip(QtGui.QApplication.translate("MainWindow", "Action A Sub", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionSubB.setText(QtGui.QApplication.translate("MainWindow", "Action B Sub", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionDelayedA.setText(QtGui.QApplication.translate("MainWindow", "Action Delayed A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionDelayedA.setToolTip(QtGui.QApplication.translate("MainWindow", "Action Delayed A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionDelayedSubA.setText(QtGui.QApplication.translate("MainWindow", "Action Delayed Sub A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionDelayedSubA.setToolTip(QtGui.QApplication.translate("MainWindow", "Action Delayed Sub A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionCheckableA.setText(QtGui.QApplication.translate("MainWindow", "Action Checkable A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionCheckableA.setToolTip(QtGui.QApplication.translate("MainWindow", "Action Checkable A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionCheckableSubAChecked.setText(QtGui.QApplication.translate("MainWindow", "Action Checkable Sub A Checked", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionCheckableSubAChecked.setToolTip(QtGui.QApplication.translate("MainWindow", "Action Checkable Sub A Checked", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionCheckableSubAUnchecked.setText(QtGui.QApplication.translate("MainWindow", "Action Checkable Sub A Unchecked", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionCheckableSubAUnchecked.setToolTip(QtGui.QApplication.translate("MainWindow", "Action Checkable Sub A Unchecked", None, QtGui.QApplication.UnicodeUTF8))

