# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw_views_widgets_containers.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.ContainerContainers = QtWidgets.QWidget()
        self.ContainerContainers.setObjectName("ContainerContainers")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.ContainerContainers)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.groupBoxDis = QtWidgets.QGroupBox(self.ContainerContainers)
        self.groupBoxDis.setEnabled(False)
        self.groupBoxDis.setObjectName("groupBoxDis")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxDis)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBoxDis)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout_29.addWidget(self.groupBoxDis, 1, 2, 1, 1)
        self.toolBoxDis = QtWidgets.QToolBox(self.ContainerContainers)
        self.toolBoxDis.setEnabled(False)
        self.toolBoxDis.setObjectName("toolBoxDis")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 196, 73))
        self.page_4.setObjectName("page_4")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_93 = QtWidgets.QLabel(self.page_4)
        self.label_93.setObjectName("label_93")
        self.gridLayout_23.addWidget(self.label_93, 2, 0, 1, 1)
        self.toolBoxDis.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 163, 38))
        self.page_5.setObjectName("page_5")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_94 = QtWidgets.QLabel(self.page_5)
        self.label_94.setObjectName("label_94")
        self.gridLayout_24.addWidget(self.label_94, 0, 0, 1, 1)
        self.toolBoxDis.addItem(self.page_5, "")
        self.gridLayout_29.addWidget(self.toolBoxDis, 3, 2, 1, 1)
        self.mdiAreaDis = QtWidgets.QMdiArea(self.ContainerContainers)
        self.mdiAreaDis.setEnabled(False)
        self.mdiAreaDis.setObjectName("mdiAreaDis")
        self.subwindow1Dis = QtWidgets.QWidget()
        self.subwindow1Dis.setObjectName("subwindow1Dis")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.subwindow1Dis)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_98 = QtWidgets.QLabel(self.subwindow1Dis)
        self.label_98.setObjectName("label_98")
        self.verticalLayout_7.addWidget(self.label_98)
        self.subwindow2Dis = QtWidgets.QWidget()
        self.subwindow2Dis.setObjectName("subwindow2Dis")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.subwindow2Dis)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_99 = QtWidgets.QLabel(self.subwindow2Dis)
        self.label_99.setObjectName("label_99")
        self.verticalLayout_8.addWidget(self.label_99)
        self.gridLayout_29.addWidget(self.mdiAreaDis, 7, 2, 1, 1)
        self.mdiArea = QtWidgets.QMdiArea(self.ContainerContainers)
        self.mdiArea.setObjectName("mdiArea")
        self.subwindow1 = QtWidgets.QWidget()
        self.subwindow1.setObjectName("subwindow1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.subwindow1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_28 = QtWidgets.QLabel(self.subwindow1)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_5.addWidget(self.label_28)
        self.subwindow2 = QtWidgets.QWidget()
        self.subwindow2.setObjectName("subwindow2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.subwindow2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_40 = QtWidgets.QLabel(self.subwindow2)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_6.addWidget(self.label_40)
        self.gridLayout_29.addWidget(self.mdiArea, 7, 1, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.ContainerContainers)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_44 = QtWidgets.QLabel(self.page1)
        self.label_44.setObjectName("label_44")
        self.gridLayout_12.addWidget(self.label_44, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_45 = QtWidgets.QLabel(self.page2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_13.addWidget(self.label_45, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page2)
        self.gridLayout_29.addWidget(self.stackedWidget, 4, 1, 1, 1)
        self.stackedWidgetDis = QtWidgets.QStackedWidget(self.ContainerContainers)
        self.stackedWidgetDis.setEnabled(False)
        self.stackedWidgetDis.setObjectName("stackedWidgetDis")
        self.page1Dis = QtWidgets.QWidget()
        self.page1Dis.setObjectName("page1Dis")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.page1Dis)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_95 = QtWidgets.QLabel(self.page1Dis)
        self.label_95.setObjectName("label_95")
        self.gridLayout_26.addWidget(self.label_95, 0, 0, 1, 1)
        self.stackedWidgetDis.addWidget(self.page1Dis)
        self.page2Dis = QtWidgets.QWidget()
        self.page2Dis.setObjectName("page2Dis")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.page2Dis)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_96 = QtWidgets.QLabel(self.page2Dis)
        self.label_96.setObjectName("label_96")
        self.gridLayout_27.addWidget(self.label_96, 0, 0, 1, 1)
        self.stackedWidgetDis.addWidget(self.page2Dis)
        self.gridLayout_29.addWidget(self.stackedWidgetDis, 4, 2, 1, 1)
        self.scrollAreaDis = QtWidgets.QScrollArea(self.ContainerContainers)
        self.scrollAreaDis.setEnabled(False)
        self.scrollAreaDis.setWidgetResizable(True)
        self.scrollAreaDis.setObjectName("scrollAreaDis")
        self.scrollAreaWidgetContentsDis = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsDis.setGeometry(QtCore.QRect(0, 0, 181, 246))
        self.scrollAreaWidgetContentsDis.setObjectName("scrollAreaWidgetContentsDis")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContentsDis)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_84 = QtWidgets.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_3.addWidget(self.label_84)
        self.label_85 = QtWidgets.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_3.addWidget(self.label_85)
        self.label_86 = QtWidgets.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_3.addWidget(self.label_86)
        self.label_87 = QtWidgets.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_87.setObjectName("label_87")
        self.verticalLayout_3.addWidget(self.label_87)
        self.label_88 = QtWidgets.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_88.setObjectName("label_88")
        self.verticalLayout_3.addWidget(self.label_88)
        self.label_89 = QtWidgets.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_89.setObjectName("label_89")
        self.verticalLayout_3.addWidget(self.label_89)
        self.label_90 = QtWidgets.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_90.setObjectName("label_90")
        self.verticalLayout_3.addWidget(self.label_90)
        self.label_91 = QtWidgets.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_91.setObjectName("label_91")
        self.verticalLayout_3.addWidget(self.label_91)
        self.label_92 = QtWidgets.QLabel(self.scrollAreaWidgetContentsDis)
        self.label_92.setObjectName("label_92")
        self.verticalLayout_3.addWidget(self.label_92)
        self.scrollAreaDis.setWidget(self.scrollAreaWidgetContentsDis)
        self.gridLayout_29.addWidget(self.scrollAreaDis, 2, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.ContainerContainers)
        self.widget.setObjectName("widget")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_47 = QtWidgets.QLabel(self.widget)
        self.label_47.setObjectName("label_47")
        self.gridLayout_17.addWidget(self.label_47, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.widget, 6, 1, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_100.setFont(font)
        self.label_100.setObjectName("label_100")
        self.gridLayout_29.addWidget(self.label_100, 0, 1, 1, 1)
        self.frameDis = QtWidgets.QFrame(self.ContainerContainers)
        self.frameDis.setEnabled(False)
        self.frameDis.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDis.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDis.setObjectName("frameDis")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.frameDis)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_3 = QtWidgets.QLabel(self.frameDis)
        self.label_3.setObjectName("label_3")
        self.gridLayout_25.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.frameDis, 5, 2, 1, 1)
        self.toolBox = QtWidgets.QToolBox(self.ContainerContainers)
        self.toolBox.setObjectName("toolBox")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setGeometry(QtCore.QRect(0, 0, 196, 73))
        self.page_1.setObjectName("page_1")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_41 = QtWidgets.QLabel(self.page_1)
        self.label_41.setObjectName("label_41")
        self.gridLayout_14.addWidget(self.label_41, 2, 0, 1, 1)
        self.toolBox.addItem(self.page_1, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 163, 38))
        self.page_2.setObjectName("page_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_42 = QtWidgets.QLabel(self.page_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_15.addWidget(self.label_42, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_2, "")
        self.gridLayout_29.addWidget(self.toolBox, 3, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.ContainerContainers)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_16.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.frame, 5, 1, 1, 1)
        self.widgetDis = QtWidgets.QWidget(self.ContainerContainers)
        self.widgetDis.setEnabled(False)
        self.widgetDis.setObjectName("widgetDis")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.widgetDis)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.label_97 = QtWidgets.QLabel(self.widgetDis)
        self.label_97.setObjectName("label_97")
        self.gridLayout_28.addWidget(self.label_97, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.widgetDis, 6, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.ContainerContainers)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.groupBox, 1, 1, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_101.setFont(font)
        self.label_101.setObjectName("label_101")
        self.gridLayout_29.addWidget(self.label_101, 0, 2, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_102.setFont(font)
        self.label_102.setObjectName("label_102")
        self.gridLayout_29.addWidget(self.label_102, 1, 0, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_103.setFont(font)
        self.label_103.setObjectName("label_103")
        self.gridLayout_29.addWidget(self.label_103, 2, 0, 1, 1)
        self.label_104 = QtWidgets.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_104.setFont(font)
        self.label_104.setObjectName("label_104")
        self.gridLayout_29.addWidget(self.label_104, 3, 0, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_105.setFont(font)
        self.label_105.setObjectName("label_105")
        self.gridLayout_29.addWidget(self.label_105, 4, 0, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_106.setFont(font)
        self.label_106.setObjectName("label_106")
        self.gridLayout_29.addWidget(self.label_106, 5, 0, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_107.setFont(font)
        self.label_107.setObjectName("label_107")
        self.gridLayout_29.addWidget(self.label_107, 6, 0, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.ContainerContainers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_108.setFont(font)
        self.label_108.setObjectName("label_108")
        self.gridLayout_29.addWidget(self.label_108, 7, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.ContainerContainers)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 181, 246))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_2.addWidget(self.label_43)
        self.label_63 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_2.addWidget(self.label_63)
        self.label_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_2.addWidget(self.label_66)
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_2.addWidget(self.label_67)
        self.label_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_68.setObjectName("label_68")
        self.verticalLayout_2.addWidget(self.label_68)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_2.addWidget(self.label_46)
        self.label_69 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_2.addWidget(self.label_69)
        self.label_64 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_2.addWidget(self.label_64)
        self.label_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_2.addWidget(self.label_65)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_29.addWidget(self.scrollArea, 2, 1, 1, 1)
        self.tabWidget.addTab(self.ContainerContainers, "")
        self.ContainerContainersTab = QtWidgets.QWidget()
        self.ContainerContainersTab.setObjectName("ContainerContainersTab")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.ContainerContainersTab)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.tabWidgetNorth = QtWidgets.QTabWidget(self.ContainerContainersTab)
        self.tabWidgetNorth.setDocumentMode(False)
        self.tabWidgetNorth.setTabsClosable(True)
        self.tabWidgetNorth.setObjectName("tabWidgetNorth")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_52 = QtWidgets.QLabel(self.tab_7)
        self.label_52.setObjectName("label_52")
        self.gridLayout_8.addWidget(self.label_52, 0, 0, 1, 1)
        self.tabWidgetNorth.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_48 = QtWidgets.QLabel(self.tab_8)
        self.label_48.setObjectName("label_48")
        self.gridLayout_4.addWidget(self.label_48, 0, 0, 1, 1)
        self.tabWidgetNorth.addTab(self.tab_8, "")
        self.gridLayout_22.addWidget(self.tabWidgetNorth, 0, 0, 1, 1)
        self.tabWidgetWest = QtWidgets.QTabWidget(self.ContainerContainersTab)
        self.tabWidgetWest.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidgetWest.setObjectName("tabWidgetWest")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_39 = QtWidgets.QLabel(self.tab_5)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 0, 0, 1, 1)
        self.tabWidgetWest.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_54 = QtWidgets.QLabel(self.tab_6)
        self.label_54.setObjectName("label_54")
        self.gridLayout_9.addWidget(self.label_54, 0, 0, 1, 1)
        self.tabWidgetWest.addTab(self.tab_6, "")
        self.gridLayout_22.addWidget(self.tabWidgetWest, 1, 0, 1, 1)
        self.tabWidgetEast = QtWidgets.QTabWidget(self.ContainerContainersTab)
        self.tabWidgetEast.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidgetEast.setObjectName("tabWidgetEast")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_38 = QtWidgets.QLabel(self.tab_3)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 0, 0, 1, 1)
        self.tabWidgetEast.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_55 = QtWidgets.QLabel(self.tab_4)
        self.label_55.setObjectName("label_55")
        self.gridLayout_11.addWidget(self.label_55, 0, 0, 1, 1)
        self.tabWidgetEast.addTab(self.tab_4, "")
        self.gridLayout_22.addWidget(self.tabWidgetEast, 2, 0, 1, 1)
        self.tabWidgetSouth = QtWidgets.QTabWidget(self.ContainerContainersTab)
        self.tabWidgetSouth.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidgetSouth.setTabsClosable(True)
        self.tabWidgetSouth.setObjectName("tabWidgetSouth")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 0, 0, 1, 1)
        self.tabWidgetSouth.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_62 = QtWidgets.QLabel(self.tab_2)
        self.label_62.setObjectName("label_62")
        self.gridLayout_18.addWidget(self.label_62, 0, 0, 1, 1)
        self.tabWidgetSouth.addTab(self.tab_2, "")
        self.gridLayout_22.addWidget(self.tabWidgetSouth, 3, 0, 1, 1)
        self.tabWidget.addTab(self.ContainerContainersTab, "")
        self.ContainerWidgets = QtWidgets.QWidget()
        self.ContainerWidgets.setObjectName("ContainerWidgets")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.ContainerWidgets)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.listWidget = QtWidgets.QListWidget(self.ContainerWidgets)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout_7.addWidget(self.listWidget, 1, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.ContainerWidgets)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        self.gridLayout_7.addWidget(self.tableWidget, 3, 2, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.ContainerWidgets)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.treeWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout_7.addWidget(self.treeWidget, 2, 2, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.ContainerWidgets)
        self.label_58.setMinimumSize(QtCore.QSize(0, 0))
        self.label_58.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_7.addWidget(self.label_58, 3, 1, 1, 1)
        self.tableWidgetDis = QtWidgets.QTableWidget(self.ContainerWidgets)
        self.tableWidgetDis.setEnabled(False)
        self.tableWidgetDis.setObjectName("tableWidgetDis")
        self.tableWidgetDis.setColumnCount(2)
        self.tableWidgetDis.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDis.setItem(2, 1, item)
        self.gridLayout_7.addWidget(self.tableWidgetDis, 3, 3, 1, 1)
        self.listWidgetDis = QtWidgets.QListWidget(self.ContainerWidgets)
        self.listWidgetDis.setEnabled(False)
        self.listWidgetDis.setObjectName("listWidgetDis")
        item = QtWidgets.QListWidgetItem()
        self.listWidgetDis.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetDis.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetDis.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetDis.addItem(item)
        self.gridLayout_7.addWidget(self.listWidgetDis, 1, 3, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.ContainerWidgets)
        self.label_57.setMinimumSize(QtCore.QSize(0, 0))
        self.label_57.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_7.addWidget(self.label_57, 2, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.ContainerWidgets)
        self.label_56.setMinimumSize(QtCore.QSize(0, 0))
        self.label_56.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_7.addWidget(self.label_56, 1, 1, 1, 1)
        self.treeWidgetDis = QtWidgets.QTreeWidget(self.ContainerWidgets)
        self.treeWidgetDis.setEnabled(False)
        self.treeWidgetDis.setObjectName("treeWidgetDis")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetDis)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetDis)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout_7.addWidget(self.treeWidgetDis, 2, 3, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.ContainerWidgets)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.gridLayout_7.addWidget(self.label_81, 0, 2, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.ContainerWidgets)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.gridLayout_7.addWidget(self.label_82, 0, 3, 1, 1)
        self.tabWidget.addTab(self.ContainerWidgets, "")
        self.ContainerViews = QtWidgets.QWidget()
        self.ContainerViews.setObjectName("ContainerViews")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ContainerViews)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.treeView = QtWidgets.QTreeView(self.ContainerViews)
        self.treeView.setObjectName("treeView")
        self.gridLayout_5.addWidget(self.treeView, 2, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 1, 0, 1, 1)
        self.listView = QtWidgets.QListView(self.ContainerViews)
        self.listView.setObjectName("listView")
        self.gridLayout_5.addWidget(self.listView, 1, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.gridLayout_5.addWidget(self.label_59, 2, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_5.addWidget(self.label_60, 3, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.ContainerViews)
        self.tableView.setObjectName("tableView")
        self.gridLayout_5.addWidget(self.tableView, 3, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.gridLayout_5.addWidget(self.label_61, 4, 0, 1, 1)
        self.columnView = QtWidgets.QColumnView(self.ContainerViews)
        self.columnView.setObjectName("columnView")
        self.gridLayout_5.addWidget(self.columnView, 4, 1, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.gridLayout_5.addWidget(self.label_70, 0, 1, 1, 1)
        self.listViewDis = QtWidgets.QListView(self.ContainerViews)
        self.listViewDis.setEnabled(False)
        self.listViewDis.setObjectName("listViewDis")
        self.gridLayout_5.addWidget(self.listViewDis, 1, 2, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.ContainerViews)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.gridLayout_5.addWidget(self.label_80, 0, 2, 1, 1)
        self.treeViewDis = QtWidgets.QTreeView(self.ContainerViews)
        self.treeViewDis.setEnabled(False)
        self.treeViewDis.setObjectName("treeViewDis")
        self.gridLayout_5.addWidget(self.treeViewDis, 2, 2, 1, 1)
        self.tableViewDis = QtWidgets.QTableView(self.ContainerViews)
        self.tableViewDis.setEnabled(False)
        self.tableViewDis.setObjectName("tableViewDis")
        self.gridLayout_5.addWidget(self.tableViewDis, 3, 2, 1, 1)
        self.columnViewDis = QtWidgets.QColumnView(self.ContainerViews)
        self.columnViewDis.setEnabled(False)
        self.columnViewDis.setObjectName("columnViewDis")
        self.gridLayout_5.addWidget(self.columnViewDis, 4, 2, 1, 1)
        self.tabWidget.addTab(self.ContainerViews, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.label_71 = QtWidgets.QLabel(self.centralwidget)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.verticalLayout_4.addWidget(self.label_71)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 28))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuMenuSub = QtWidgets.QMenu(self.menuMenu)
        self.menuMenuSub.setObjectName("menuMenuSub")
        self.menuMenuDelayed = QtWidgets.QMenu(self.menubar)
        self.menuMenuDelayed.setObjectName("menuMenuDelayed")
        self.menuMenuSubDelayed = QtWidgets.QMenu(self.menuMenuDelayed)
        self.menuMenuSubDelayed.setObjectName("menuMenuSubDelayed")
        self.menuMenuCheckale = QtWidgets.QMenu(self.menubar)
        self.menuMenuCheckale.setObjectName("menuMenuCheckale")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBarDelayed = QtWidgets.QToolBar(MainWindow)
        self.toolBarDelayed.setObjectName("toolBarDelayed")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarDelayed)
        self.toolBarCheckable = QtWidgets.QToolBar(MainWindow)
        self.toolBarCheckable.setObjectName("toolBarCheckable")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBarCheckable)
        self.actionActionA = QtWidgets.QAction(MainWindow)
        self.actionActionA.setObjectName("actionActionA")
        self.actionActionSubA = QtWidgets.QAction(MainWindow)
        self.actionActionSubA.setObjectName("actionActionSubA")
        self.actionActionSubB = QtWidgets.QAction(MainWindow)
        self.actionActionSubB.setObjectName("actionActionSubB")
        self.actionActionDelayedA = QtWidgets.QAction(MainWindow)
        self.actionActionDelayedA.setObjectName("actionActionDelayedA")
        self.actionActionDelayedSubA = QtWidgets.QAction(MainWindow)
        self.actionActionDelayedSubA.setObjectName("actionActionDelayedSubA")
        self.actionActionCheckableA = QtWidgets.QAction(MainWindow)
        self.actionActionCheckableA.setCheckable(True)
        self.actionActionCheckableA.setObjectName("actionActionCheckableA")
        self.actionActionCheckableSubAChecked = QtWidgets.QAction(MainWindow)
        self.actionActionCheckableSubAChecked.setCheckable(True)
        self.actionActionCheckableSubAChecked.setChecked(True)
        self.actionActionCheckableSubAChecked.setObjectName("actionActionCheckableSubAChecked")
        self.actionActionCheckableSubAUnchecked = QtWidgets.QAction(MainWindow)
        self.actionActionCheckableSubAUnchecked.setCheckable(True)
        self.actionActionCheckableSubAUnchecked.setObjectName("actionActionCheckableSubAUnchecked")
        self.menuMenuSub.addAction(self.actionActionSubA)
        self.menuMenuSub.addAction(self.actionActionSubB)
        self.menuMenu.addAction(self.actionActionA)
        self.menuMenu.addAction(self.menuMenuSub.menuAction())
        self.menuMenuSubDelayed.addAction(self.actionActionDelayedSubA)
        self.menuMenuDelayed.addAction(self.actionActionDelayedA)
        self.menuMenuDelayed.addAction(self.menuMenuSubDelayed.menuAction())
        self.menuMenuCheckale.addAction(self.actionActionCheckableA)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuMenuDelayed.menuAction())
        self.menubar.addAction(self.menuMenuCheckale.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionActionA)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionActionSubA)
        self.toolBar.addAction(self.actionActionSubB)
        self.toolBarDelayed.addAction(self.actionActionDelayedA)
        self.toolBarDelayed.addSeparator()
        self.toolBarDelayed.addAction(self.actionActionDelayedSubA)
        self.toolBarCheckable.addAction(self.actionActionCheckableA)
        self.toolBarCheckable.addSeparator()
        self.toolBarCheckable.addAction(self.actionActionCheckableSubAChecked)
        self.toolBarCheckable.addAction(self.actionActionCheckableSubAUnchecked)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.toolBoxDis.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidgetDis.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        self.tabWidgetNorth.setCurrentIndex(0)
        self.tabWidgetWest.setCurrentIndex(0)
        self.tabWidgetEast.setCurrentIndex(0)
        self.tabWidgetSouth.setCurrentIndex(0)
        self.toolBox.currentChanged['int'].connect(self.toolBoxDis.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.tabWidget.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.groupBoxDis.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_4.setText(_translate("MainWindow", "Inside GroupBox"))
        self.toolBoxDis.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.toolBoxDis.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.toolBoxDis.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_93.setText(_translate("MainWindow", "Inside ToolBox Page 1"))
        self.toolBoxDis.setItemText(self.toolBoxDis.indexOf(self.page_4), _translate("MainWindow", "Page 1"))
        self.label_94.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_94.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_94.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_94.setText(_translate("MainWindow", "Inside ToolBox Page 2"))
        self.toolBoxDis.setItemText(self.toolBoxDis.indexOf(self.page_5), _translate("MainWindow", "Page 2"))
        self.subwindow1Dis.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.label_98.setText(_translate("MainWindow", "Inside MDI Area 1"))
        self.subwindow2Dis.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.label_99.setText(_translate("MainWindow", "Inside MDI Area 2 "))
        self.subwindow1.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.label_28.setText(_translate("MainWindow", "Inside MDI Area 1"))
        self.subwindow2.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.label_40.setText(_translate("MainWindow", "Inside MDI Area 2 "))
        self.stackedWidget.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.stackedWidget.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.stackedWidget.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_44.setText(_translate("MainWindow", "Inside Stacked Page 1"))
        self.label_45.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_45.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_45.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_45.setText(_translate("MainWindow", "Inside Stacked Page 2"))
        self.stackedWidgetDis.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.stackedWidgetDis.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.stackedWidgetDis.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_95.setText(_translate("MainWindow", "Inside Stacked Page 1"))
        self.label_96.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_96.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_96.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_96.setText(_translate("MainWindow", "Inside Stacked Page 2"))
        self.scrollAreaDis.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.scrollAreaDis.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.scrollAreaDis.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_84.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_84.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_84.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_84.setText(_translate("MainWindow", "Inside ScroolArea"))
        self.label_85.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_85.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_85.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_85.setText(_translate("MainWindow", "ScroolArea "))
        self.label_86.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_86.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_86.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_86.setText(_translate("MainWindow", "Inside ScroolArea "))
        self.label_87.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_87.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_87.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_87.setText(_translate("MainWindow", "ScroolArea"))
        self.label_88.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_88.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_88.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_88.setText(_translate("MainWindow", "Inside ScroolArea"))
        self.label_89.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_89.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_89.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_89.setText(_translate("MainWindow", "ScroolArea"))
        self.label_90.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_90.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_90.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_90.setText(_translate("MainWindow", "Inside ScroolArea"))
        self.label_91.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_91.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_91.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_91.setText(_translate("MainWindow", "ScroolArea"))
        self.label_92.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_92.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_92.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_92.setText(_translate("MainWindow", "Inside ScroolArea"))
        self.widget.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.widget.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.widget.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_47.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_47.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_47.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_47.setText(_translate("MainWindow", "Inside Widget"))
        self.label_100.setText(_translate("MainWindow", "Enabled"))
        self.frameDis.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.frameDis.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.frameDis.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_3.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_3.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_3.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_3.setText(_translate("MainWindow", "Inside Frame"))
        self.toolBox.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.toolBox.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.toolBox.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_41.setText(_translate("MainWindow", "Inside ToolBox Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_1), _translate("MainWindow", "Page 1"))
        self.label_42.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_42.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_42.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_42.setText(_translate("MainWindow", "Inside ToolBox Page 2"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Page 2"))
        self.frame.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.frame.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.frame.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_2.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_2.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_2.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_2.setText(_translate("MainWindow", "Inside Frame"))
        self.widgetDis.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.widgetDis.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.widgetDis.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_97.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_97.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_97.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_97.setText(_translate("MainWindow", "Inside Widget"))
        self.groupBox.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.groupBox.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.groupBox.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label.setText(_translate("MainWindow", "Inside GroupBox"))
        self.label_101.setText(_translate("MainWindow", "Disabled"))
        self.label_102.setText(_translate("MainWindow", "GroupBox"))
        self.label_103.setText(_translate("MainWindow", "ScroolArea"))
        self.label_104.setText(_translate("MainWindow", "ToolBox"))
        self.label_105.setText(_translate("MainWindow", "Stacked"))
        self.label_106.setText(_translate("MainWindow", "Frame"))
        self.label_107.setText(_translate("MainWindow", "Widget"))
        self.label_108.setText(_translate("MainWindow", "MDI Area"))
        self.scrollArea.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.scrollArea.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.scrollArea.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_43.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_43.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_43.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_43.setText(_translate("MainWindow", "Inside ScroolArea"))
        self.label_63.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_63.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_63.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_63.setText(_translate("MainWindow", "ScroolArea "))
        self.label_66.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_66.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_66.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_66.setText(_translate("MainWindow", "Inside ScroolArea "))
        self.label_67.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_67.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_67.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_67.setText(_translate("MainWindow", "ScroolArea"))
        self.label_68.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_68.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_68.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_68.setText(_translate("MainWindow", "Inside ScroolArea"))
        self.label_46.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_46.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_46.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_46.setText(_translate("MainWindow", "ScroolArea"))
        self.label_69.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_69.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_69.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_69.setText(_translate("MainWindow", "Inside ScroolArea"))
        self.label_64.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_64.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_64.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_64.setText(_translate("MainWindow", "ScroolArea"))
        self.label_65.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_65.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_65.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_65.setText(_translate("MainWindow", "Inside ScroolArea"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ContainerContainers), _translate("MainWindow", "Containers"))
        self.label_52.setText(_translate("MainWindow", "Inside TabWidget North Closable Tab 1"))
        self.tabWidgetNorth.setTabText(self.tabWidgetNorth.indexOf(self.tab_7), _translate("MainWindow", "Tab 1"))
        self.label_48.setText(_translate("MainWindow", "Inside TabWidget North Closable Tab 2"))
        self.tabWidgetNorth.setTabText(self.tabWidgetNorth.indexOf(self.tab_8), _translate("MainWindow", "Tab 2"))
        self.label_39.setText(_translate("MainWindow", "Inside TabWidget West Tab 1"))
        self.tabWidgetWest.setTabText(self.tabWidgetWest.indexOf(self.tab_5), _translate("MainWindow", "Tab 1"))
        self.label_54.setText(_translate("MainWindow", "Inside TabWidget West Tab 2"))
        self.tabWidgetWest.setTabText(self.tabWidgetWest.indexOf(self.tab_6), _translate("MainWindow", "Tab 2"))
        self.label_38.setText(_translate("MainWindow", "Inside TabWidget East Tab 1"))
        self.tabWidgetEast.setTabText(self.tabWidgetEast.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.label_55.setText(_translate("MainWindow", "Inside TabWidget East Tab 2"))
        self.tabWidgetEast.setTabText(self.tabWidgetEast.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.label_34.setText(_translate("MainWindow", "Inside TabWidget South Closable Tab 1"))
        self.tabWidgetSouth.setTabText(self.tabWidgetSouth.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_62.setText(_translate("MainWindow", "Inside TabWidget South Closable Tab 2"))
        self.tabWidgetSouth.setTabText(self.tabWidgetSouth.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ContainerContainersTab), _translate("MainWindow", "Containers - Tabs"))
        self.listWidget.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.listWidget.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.listWidget.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tableWidget.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.tableWidget.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.tableWidget.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "1.23"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Hello"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "1,45"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "Olá"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "12/12/2012"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "Oui"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.treeWidget.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.treeWidget.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.treeWidget.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "New Column"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "New Column"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "New Item"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.treeWidget.topLevelItem(0).child(0).setText(1, _translate("MainWindow", "Test"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "New Item"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_58.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_58.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_58.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_58.setText(_translate("MainWindow", "TableWidget"))
        item = self.tableWidgetDis.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetDis.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetDis.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetDis.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidgetDis.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        __sortingEnabled = self.tableWidgetDis.isSortingEnabled()
        self.tableWidgetDis.setSortingEnabled(False)
        item = self.tableWidgetDis.item(0, 0)
        item.setText(_translate("MainWindow", "1.23"))
        item = self.tableWidgetDis.item(0, 1)
        item.setText(_translate("MainWindow", "Hello"))
        item = self.tableWidgetDis.item(1, 0)
        item.setText(_translate("MainWindow", "1,45"))
        item = self.tableWidgetDis.item(1, 1)
        item.setText(_translate("MainWindow", "Olá"))
        item = self.tableWidgetDis.item(2, 0)
        item.setText(_translate("MainWindow", "12/12/2012"))
        item = self.tableWidgetDis.item(2, 1)
        item.setText(_translate("MainWindow", "Oui"))
        self.tableWidgetDis.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidgetDis.isSortingEnabled()
        self.listWidgetDis.setSortingEnabled(False)
        item = self.listWidgetDis.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidgetDis.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidgetDis.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidgetDis.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidgetDis.setSortingEnabled(__sortingEnabled)
        self.label_57.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_57.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_57.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_57.setText(_translate("MainWindow", "TreeWidget"))
        self.label_56.setToolTip(_translate("MainWindow", "This is a tool tip"))
        self.label_56.setStatusTip(_translate("MainWindow", "This is a status tip"))
        self.label_56.setWhatsThis(_translate("MainWindow", "This is \"what is this\""))
        self.label_56.setText(_translate("MainWindow", "ListWidget"))
        self.treeWidgetDis.setSortingEnabled(True)
        self.treeWidgetDis.headerItem().setText(0, _translate("MainWindow", "New Column"))
        self.treeWidgetDis.headerItem().setText(1, _translate("MainWindow", "New Column"))
        __sortingEnabled = self.treeWidgetDis.isSortingEnabled()
        self.treeWidgetDis.setSortingEnabled(False)
        self.treeWidgetDis.topLevelItem(0).setText(0, _translate("MainWindow", "New Item"))
        self.treeWidgetDis.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.treeWidgetDis.topLevelItem(0).child(0).setText(1, _translate("MainWindow", "Test"))
        self.treeWidgetDis.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.treeWidgetDis.topLevelItem(1).setText(0, _translate("MainWindow", "New Item"))
        self.treeWidgetDis.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.treeWidgetDis.setSortingEnabled(__sortingEnabled)
        self.label_81.setText(_translate("MainWindow", "Enabled"))
        self.label_82.setText(_translate("MainWindow", "Disabled"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ContainerWidgets), _translate("MainWindow", "Widgets"))
        self.label_27.setText(_translate("MainWindow", "ListView"))
        self.label_59.setText(_translate("MainWindow", "TreeView"))
        self.label_60.setText(_translate("MainWindow", "TableView"))
        self.label_61.setText(_translate("MainWindow", "ColunmView"))
        self.label_70.setText(_translate("MainWindow", "Enabled"))
        self.label_80.setText(_translate("MainWindow", "Disabled"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ContainerViews), _translate("MainWindow", "Views"))
        self.label_71.setText(_translate("MainWindow", "Inside CentralWidget"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuMenuSub.setTitle(_translate("MainWindow", "Menu Sub"))
        self.menuMenuDelayed.setTitle(_translate("MainWindow", "Menu Delayed"))
        self.menuMenuSubDelayed.setTitle(_translate("MainWindow", "Menu Sub Delayed"))
        self.menuMenuCheckale.setTitle(_translate("MainWindow", "Menu Checkable"))
        self.menuAbout.setTitle(_translate("MainWindow", "About QDarkStyle"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBarDelayed.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBarCheckable.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionActionA.setText(_translate("MainWindow", "Action A"))
        self.actionActionSubA.setText(_translate("MainWindow", "Action A Sub"))
        self.actionActionSubA.setToolTip(_translate("MainWindow", "Action A Sub"))
        self.actionActionSubB.setText(_translate("MainWindow", "Action B Sub"))
        self.actionActionDelayedA.setText(_translate("MainWindow", "Action Delayed A"))
        self.actionActionDelayedA.setToolTip(_translate("MainWindow", "Action Delayed A"))
        self.actionActionDelayedSubA.setText(_translate("MainWindow", "Action Delayed Sub A"))
        self.actionActionDelayedSubA.setToolTip(_translate("MainWindow", "Action Delayed Sub A"))
        self.actionActionCheckableA.setText(_translate("MainWindow", "Action Checkable A"))
        self.actionActionCheckableA.setToolTip(_translate("MainWindow", "Action Checkable A"))
        self.actionActionCheckableSubAChecked.setText(_translate("MainWindow", "Action Checkable Sub A Checked"))
        self.actionActionCheckableSubAChecked.setToolTip(_translate("MainWindow", "Action Checkable Sub A Checked"))
        self.actionActionCheckableSubAUnchecked.setText(_translate("MainWindow", "Action Checkable Sub A Unchecked"))
        self.actionActionCheckableSubAUnchecked.setToolTip(_translate("MainWindow", "Action Checkable Sub A Unchecked"))

